service: reservation
frameworkVersion: '>=1.1.0 <2.0.0'
provider:
  name: aws
  runtime: nodejs8.10
  environment:
    stage: ${self:custom.stage}
    tableReservation: ${self:custom.tableReservation}
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - dynamodb:*
        - lambda:InvokeFunction
        - lambda:InvokeAsync
      Resource: '*'

plugins:
  - serverless-domain-manager

custom:
  stage: ${opt:stage, self:provider.stage}
  tableThroughputs:
    prod: 5
    default: 1
  tableThroughput: ${self:custom.tableThroughputs.${self:custom.stage}, self:custom.tableThroughputs.default}
  domains:
    prod: api.tryclicker.com
    release: api-release.tryclicker.com
    dev: api-dev.tryclicker.com
  customDomain:
    domainName: ${self:custom.domains.${self:custom.stage}}
    basePath: reservations
    certificateName: 'api.tryclicker.com'
    stage: ${self:custom.stage}
    createRoute53Record: true
    endpointType: 'edge'
  tableReservation: reservations-${self:custom.stage}
resources:
  Resources:
    ReservationTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: ${self:custom.tableReservation}
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: id
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: ${self:custom.tableThroughput}
          WriteCapacityUnits: ${self:custom.tableThroughput}

functions:
  health:
    handler: reservation.health
    events:
      - http:
          path: health
          method: get
          cors: true
  all:
    handler: reservation.all
    events:
      - http:
          path: ''
          method: get
          cors: true
  active:
    handler: reservation.active
    events:
      - http:
          path: 'active'
          method: get
          cors: true
  get:
    handler: reservation.get
    events:
      - http:
          path: '{id}'
          method: get
          cors: true
  create:
    handler: reservation.create
    events:
      - http:
          path: ''
          method: post
          cors: true
  cancel:
    handler: reservation.cancel
    events:
      - http:
          path: '{id}'
          method: delete
          cors: true
  changeChannel:
    handler: reservation.changeChannel
    events:
      - http:
          path: '{id}/channel'
          method: put
          cors: true
  changeTime:
    handler: reservation.changeTime
    events:
      - http:
          path: '{id}/time'
          method: put
          cors: true
