// flow-typed signature: f77dc184bb5d79eac756957a73a5c00a
// flow-typed version: <<STUB>>/airtable_v0.7.2/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'airtable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'airtable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'airtable/build/airtable.browser' {
  declare module.exports: any;
}

declare module 'airtable/lib/airtable_error' {
  declare module.exports: any;
}

declare module 'airtable/lib/airtable' {
  declare module.exports: any;
}

declare module 'airtable/lib/base' {
  declare module.exports: any;
}

declare module 'airtable/lib/callback_to_promise' {
  declare module.exports: any;
}

declare module 'airtable/lib/deprecate' {
  declare module.exports: any;
}

declare module 'airtable/lib/has' {
  declare module.exports: any;
}

declare module 'airtable/lib/object_to_query_param_string' {
  declare module.exports: any;
}

declare module 'airtable/lib/package_version_browser' {
  declare module.exports: any;
}

declare module 'airtable/lib/package_version' {
  declare module.exports: any;
}

declare module 'airtable/lib/query' {
  declare module.exports: any;
}

declare module 'airtable/lib/record' {
  declare module.exports: any;
}

declare module 'airtable/lib/run_action' {
  declare module.exports: any;
}

declare module 'airtable/lib/table' {
  declare module.exports: any;
}

declare module 'airtable/lib/typecheck' {
  declare module.exports: any;
}

// Filename aliases
declare module 'airtable/build/airtable.browser.js' {
  declare module.exports: $Exports<'airtable/build/airtable.browser'>;
}
declare module 'airtable/lib/airtable_error.js' {
  declare module.exports: $Exports<'airtable/lib/airtable_error'>;
}
declare module 'airtable/lib/airtable.js' {
  declare module.exports: $Exports<'airtable/lib/airtable'>;
}
declare module 'airtable/lib/base.js' {
  declare module.exports: $Exports<'airtable/lib/base'>;
}
declare module 'airtable/lib/callback_to_promise.js' {
  declare module.exports: $Exports<'airtable/lib/callback_to_promise'>;
}
declare module 'airtable/lib/deprecate.js' {
  declare module.exports: $Exports<'airtable/lib/deprecate'>;
}
declare module 'airtable/lib/has.js' {
  declare module.exports: $Exports<'airtable/lib/has'>;
}
declare module 'airtable/lib/object_to_query_param_string.js' {
  declare module.exports: $Exports<'airtable/lib/object_to_query_param_string'>;
}
declare module 'airtable/lib/package_version_browser.js' {
  declare module.exports: $Exports<'airtable/lib/package_version_browser'>;
}
declare module 'airtable/lib/package_version.js' {
  declare module.exports: $Exports<'airtable/lib/package_version'>;
}
declare module 'airtable/lib/query.js' {
  declare module.exports: $Exports<'airtable/lib/query'>;
}
declare module 'airtable/lib/record.js' {
  declare module.exports: $Exports<'airtable/lib/record'>;
}
declare module 'airtable/lib/run_action.js' {
  declare module.exports: $Exports<'airtable/lib/run_action'>;
}
declare module 'airtable/lib/table.js' {
  declare module.exports: $Exports<'airtable/lib/table'>;
}
declare module 'airtable/lib/typecheck.js' {
  declare module.exports: $Exports<'airtable/lib/typecheck'>;
}
