// flow-typed signature: ded7684350652846842e4f11ba585714
// flow-typed version: <<STUB>>/aws-xray-sdk_v2.5.0/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'aws-xray-sdk'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'aws-xray-sdk' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'aws-xray-sdk/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'aws-xray-sdk/lib/index.js' {
  declare module.exports: $Exports<'aws-xray-sdk/lib/index'>;
}
