// flow-typed signature: a1ffeeb55cc63bc1b5e538f0dd97032c
// flow-typed version: <<STUB>>/camelcase-keys_v6.1.0/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'camelcase-keys'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'camelcase-keys' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'camelcase-keys/index' {
  declare module.exports: $Exports<'camelcase-keys'>;
}
declare module 'camelcase-keys/index.js' {
  declare module.exports: $Exports<'camelcase-keys'>;
}
