// flow-typed signature: 53573d2f744cd76bd8a2df5ceaefe7d5
// flow-typed version: <<STUB>>/dynamoose_v1.7.2/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dynamoose'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dynamoose' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dynamoose/dist/Attribute' {
  declare module.exports: any;
}

declare module 'dynamoose/dist/Dynamoose' {
  declare module.exports: any;
}

declare module 'dynamoose/dist/errors' {
  declare module.exports: any;
}

declare module 'dynamoose/dist/index' {
  declare module.exports: any;
}

declare module 'dynamoose/dist/Listener' {
  declare module.exports: any;
}

declare module 'dynamoose/dist/Model' {
  declare module.exports: any;
}

declare module 'dynamoose/dist/Plugin' {
  declare module.exports: any;
}

declare module 'dynamoose/dist/Query' {
  declare module.exports: any;
}

declare module 'dynamoose/dist/reserved-keywords' {
  declare module.exports: any;
}

declare module 'dynamoose/dist/Scan' {
  declare module.exports: any;
}

declare module 'dynamoose/dist/Schema' {
  declare module.exports: any;
}

declare module 'dynamoose/dist/Table' {
  declare module.exports: any;
}

declare module 'dynamoose/dist/VirtualType' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dynamoose/dist/Attribute.js' {
  declare module.exports: $Exports<'dynamoose/dist/Attribute'>;
}
declare module 'dynamoose/dist/Dynamoose.js' {
  declare module.exports: $Exports<'dynamoose/dist/Dynamoose'>;
}
declare module 'dynamoose/dist/errors.js' {
  declare module.exports: $Exports<'dynamoose/dist/errors'>;
}
declare module 'dynamoose/dist/index.js' {
  declare module.exports: $Exports<'dynamoose/dist/index'>;
}
declare module 'dynamoose/dist/Listener.js' {
  declare module.exports: $Exports<'dynamoose/dist/Listener'>;
}
declare module 'dynamoose/dist/Model.js' {
  declare module.exports: $Exports<'dynamoose/dist/Model'>;
}
declare module 'dynamoose/dist/Plugin.js' {
  declare module.exports: $Exports<'dynamoose/dist/Plugin'>;
}
declare module 'dynamoose/dist/Query.js' {
  declare module.exports: $Exports<'dynamoose/dist/Query'>;
}
declare module 'dynamoose/dist/reserved-keywords.js' {
  declare module.exports: $Exports<'dynamoose/dist/reserved-keywords'>;
}
declare module 'dynamoose/dist/Scan.js' {
  declare module.exports: $Exports<'dynamoose/dist/Scan'>;
}
declare module 'dynamoose/dist/Schema.js' {
  declare module.exports: $Exports<'dynamoose/dist/Schema'>;
}
declare module 'dynamoose/dist/Table.js' {
  declare module.exports: $Exports<'dynamoose/dist/Table'>;
}
declare module 'dynamoose/dist/VirtualType.js' {
  declare module.exports: $Exports<'dynamoose/dist/VirtualType'>;
}
