// flow-typed signature: b6f3f38e17393482606af7dd9f250fa1
// flow-typed version: <<STUB>>/geolib_v2.0.24/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'geolib'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'geolib' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'geolib/dist/geolib.elevation' {
  declare module.exports: any;
}

declare module 'geolib/dist/geolib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'geolib/dist/geolib.elevation.js' {
  declare module.exports: $Exports<'geolib/dist/geolib.elevation'>;
}
declare module 'geolib/dist/geolib.js' {
  declare module.exports: $Exports<'geolib/dist/geolib'>;
}
