// flow-typed signature: da5d7755303192a72161a4c9b6b70cda
// flow-typed version: <<STUB>>/hubspot_v2.0.0/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'hubspot'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'hubspot' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'hubspot/config' {
  declare module.exports: any;
}

declare module 'hubspot/lib/broadcast' {
  declare module.exports: any;
}

declare module 'hubspot/lib/campaign' {
  declare module.exports: any;
}

declare module 'hubspot/lib/client' {
  declare module.exports: any;
}

declare module 'hubspot/lib/company_property_group' {
  declare module.exports: any;
}

declare module 'hubspot/lib/company_property' {
  declare module.exports: any;
}

declare module 'hubspot/lib/company' {
  declare module.exports: any;
}

declare module 'hubspot/lib/contact_property' {
  declare module.exports: any;
}

declare module 'hubspot/lib/contact' {
  declare module.exports: any;
}

declare module 'hubspot/lib/deal_property_group' {
  declare module.exports: any;
}

declare module 'hubspot/lib/deal_property' {
  declare module.exports: any;
}

declare module 'hubspot/lib/deal' {
  declare module.exports: any;
}

declare module 'hubspot/lib/emails' {
  declare module.exports: any;
}

declare module 'hubspot/lib/engagement' {
  declare module.exports: any;
}

declare module 'hubspot/lib/file' {
  declare module.exports: any;
}

declare module 'hubspot/lib/list' {
  declare module.exports: any;
}

declare module 'hubspot/lib/oauth' {
  declare module.exports: any;
}

declare module 'hubspot/lib/owner' {
  declare module.exports: any;
}

declare module 'hubspot/lib/page' {
  declare module.exports: any;
}

declare module 'hubspot/lib/pipeline' {
  declare module.exports: any;
}

declare module 'hubspot/lib/subscription' {
  declare module.exports: any;
}

declare module 'hubspot/lib/timeline' {
  declare module.exports: any;
}

declare module 'hubspot/lib/utils/guid' {
  declare module.exports: any;
}

declare module 'hubspot/lib/workflow' {
  declare module.exports: any;
}

declare module 'hubspot/test/broadcasts' {
  declare module.exports: any;
}

declare module 'hubspot/test/campaigns' {
  declare module.exports: any;
}

declare module 'hubspot/test/client' {
  declare module.exports: any;
}

declare module 'hubspot/test/companies' {
  declare module.exports: any;
}

declare module 'hubspot/test/company_properties_groups' {
  declare module.exports: any;
}

declare module 'hubspot/test/company_properties' {
  declare module.exports: any;
}

declare module 'hubspot/test/contact_properties' {
  declare module.exports: any;
}

declare module 'hubspot/test/contacts' {
  declare module.exports: any;
}

declare module 'hubspot/test/deal_properties_group' {
  declare module.exports: any;
}

declare module 'hubspot/test/deal_properties' {
  declare module.exports: any;
}

declare module 'hubspot/test/deals' {
  declare module.exports: any;
}

declare module 'hubspot/test/engagements' {
  declare module.exports: any;
}

declare module 'hubspot/test/files' {
  declare module.exports: any;
}

declare module 'hubspot/test/helpers/fake_hubspot_api' {
  declare module.exports: any;
}

declare module 'hubspot/test/helpers/nock_helper' {
  declare module.exports: any;
}

declare module 'hubspot/test/lists' {
  declare module.exports: any;
}

declare module 'hubspot/test/oauth' {
  declare module.exports: any;
}

declare module 'hubspot/test/owners' {
  declare module.exports: any;
}

declare module 'hubspot/test/page' {
  declare module.exports: any;
}

declare module 'hubspot/test/pipelines' {
  declare module.exports: any;
}

declare module 'hubspot/test/subscriptions' {
  declare module.exports: any;
}

declare module 'hubspot/test/timeline' {
  declare module.exports: any;
}

declare module 'hubspot/test/workflows' {
  declare module.exports: any;
}

// Filename aliases
declare module 'hubspot/config.js' {
  declare module.exports: $Exports<'hubspot/config'>;
}
declare module 'hubspot/index' {
  declare module.exports: $Exports<'hubspot'>;
}
declare module 'hubspot/index.js' {
  declare module.exports: $Exports<'hubspot'>;
}
declare module 'hubspot/lib/broadcast.js' {
  declare module.exports: $Exports<'hubspot/lib/broadcast'>;
}
declare module 'hubspot/lib/campaign.js' {
  declare module.exports: $Exports<'hubspot/lib/campaign'>;
}
declare module 'hubspot/lib/client.js' {
  declare module.exports: $Exports<'hubspot/lib/client'>;
}
declare module 'hubspot/lib/company_property_group.js' {
  declare module.exports: $Exports<'hubspot/lib/company_property_group'>;
}
declare module 'hubspot/lib/company_property.js' {
  declare module.exports: $Exports<'hubspot/lib/company_property'>;
}
declare module 'hubspot/lib/company.js' {
  declare module.exports: $Exports<'hubspot/lib/company'>;
}
declare module 'hubspot/lib/contact_property.js' {
  declare module.exports: $Exports<'hubspot/lib/contact_property'>;
}
declare module 'hubspot/lib/contact.js' {
  declare module.exports: $Exports<'hubspot/lib/contact'>;
}
declare module 'hubspot/lib/deal_property_group.js' {
  declare module.exports: $Exports<'hubspot/lib/deal_property_group'>;
}
declare module 'hubspot/lib/deal_property.js' {
  declare module.exports: $Exports<'hubspot/lib/deal_property'>;
}
declare module 'hubspot/lib/deal.js' {
  declare module.exports: $Exports<'hubspot/lib/deal'>;
}
declare module 'hubspot/lib/emails.js' {
  declare module.exports: $Exports<'hubspot/lib/emails'>;
}
declare module 'hubspot/lib/engagement.js' {
  declare module.exports: $Exports<'hubspot/lib/engagement'>;
}
declare module 'hubspot/lib/file.js' {
  declare module.exports: $Exports<'hubspot/lib/file'>;
}
declare module 'hubspot/lib/list.js' {
  declare module.exports: $Exports<'hubspot/lib/list'>;
}
declare module 'hubspot/lib/oauth.js' {
  declare module.exports: $Exports<'hubspot/lib/oauth'>;
}
declare module 'hubspot/lib/owner.js' {
  declare module.exports: $Exports<'hubspot/lib/owner'>;
}
declare module 'hubspot/lib/page.js' {
  declare module.exports: $Exports<'hubspot/lib/page'>;
}
declare module 'hubspot/lib/pipeline.js' {
  declare module.exports: $Exports<'hubspot/lib/pipeline'>;
}
declare module 'hubspot/lib/subscription.js' {
  declare module.exports: $Exports<'hubspot/lib/subscription'>;
}
declare module 'hubspot/lib/timeline.js' {
  declare module.exports: $Exports<'hubspot/lib/timeline'>;
}
declare module 'hubspot/lib/utils/guid.js' {
  declare module.exports: $Exports<'hubspot/lib/utils/guid'>;
}
declare module 'hubspot/lib/workflow.js' {
  declare module.exports: $Exports<'hubspot/lib/workflow'>;
}
declare module 'hubspot/test/broadcasts.js' {
  declare module.exports: $Exports<'hubspot/test/broadcasts'>;
}
declare module 'hubspot/test/campaigns.js' {
  declare module.exports: $Exports<'hubspot/test/campaigns'>;
}
declare module 'hubspot/test/client.js' {
  declare module.exports: $Exports<'hubspot/test/client'>;
}
declare module 'hubspot/test/companies.js' {
  declare module.exports: $Exports<'hubspot/test/companies'>;
}
declare module 'hubspot/test/company_properties_groups.js' {
  declare module.exports: $Exports<'hubspot/test/company_properties_groups'>;
}
declare module 'hubspot/test/company_properties.js' {
  declare module.exports: $Exports<'hubspot/test/company_properties'>;
}
declare module 'hubspot/test/contact_properties.js' {
  declare module.exports: $Exports<'hubspot/test/contact_properties'>;
}
declare module 'hubspot/test/contacts.js' {
  declare module.exports: $Exports<'hubspot/test/contacts'>;
}
declare module 'hubspot/test/deal_properties_group.js' {
  declare module.exports: $Exports<'hubspot/test/deal_properties_group'>;
}
declare module 'hubspot/test/deal_properties.js' {
  declare module.exports: $Exports<'hubspot/test/deal_properties'>;
}
declare module 'hubspot/test/deals.js' {
  declare module.exports: $Exports<'hubspot/test/deals'>;
}
declare module 'hubspot/test/engagements.js' {
  declare module.exports: $Exports<'hubspot/test/engagements'>;
}
declare module 'hubspot/test/files.js' {
  declare module.exports: $Exports<'hubspot/test/files'>;
}
declare module 'hubspot/test/helpers/fake_hubspot_api.js' {
  declare module.exports: $Exports<'hubspot/test/helpers/fake_hubspot_api'>;
}
declare module 'hubspot/test/helpers/nock_helper.js' {
  declare module.exports: $Exports<'hubspot/test/helpers/nock_helper'>;
}
declare module 'hubspot/test/lists.js' {
  declare module.exports: $Exports<'hubspot/test/lists'>;
}
declare module 'hubspot/test/oauth.js' {
  declare module.exports: $Exports<'hubspot/test/oauth'>;
}
declare module 'hubspot/test/owners.js' {
  declare module.exports: $Exports<'hubspot/test/owners'>;
}
declare module 'hubspot/test/page.js' {
  declare module.exports: $Exports<'hubspot/test/page'>;
}
declare module 'hubspot/test/pipelines.js' {
  declare module.exports: $Exports<'hubspot/test/pipelines'>;
}
declare module 'hubspot/test/subscriptions.js' {
  declare module.exports: $Exports<'hubspot/test/subscriptions'>;
}
declare module 'hubspot/test/timeline.js' {
  declare module.exports: $Exports<'hubspot/test/timeline'>;
}
declare module 'hubspot/test/workflows.js' {
  declare module.exports: $Exports<'hubspot/test/workflows'>;
}
