// flow-typed signature: 717d2402200e722e087579f14eb0ff66
// flow-typed version: <<STUB>>/losant-rest_v2.3.5/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'losant-rest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'losant-rest' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'losant-rest/examples/auth' {
  declare module.exports: any;
}

declare module 'losant-rest/examples/list_devices' {
  declare module.exports: any;
}

declare module 'losant-rest/lib/api/application' {
  declare module.exports: any;
}

declare module 'losant-rest/lib/api/applicationApiToken' {
  declare module.exports: any;
}

declare module 'losant-rest/lib/api/applicationApiTokens' {
  declare module.exports: any;
}

declare module 'losant-rest/lib/api/applicationKey' {
  declare module.exports: any;
}

declare module 'losant-rest/lib/api/applicationKeys' {
  declare module.exports: any;
}

declare module 'losant-rest/lib/api/applications' {
  declare module.exports: any;
}

declare module 'losant-rest/lib/api/auditLog' {
  declare module.exports: any;
}

declare module 'losant-rest/lib/api/auditLogs' {
  declare module.exports: any;
}

declare module 'losant-rest/lib/api/auth' {
  declare module.exports: any;
}

declare module 'losant-rest/lib/api/dashboard' {
  declare module.exports: any;
}

declare module 'losant-rest/lib/api/dashboards' {
  declare module.exports: any;
}

declare module 'losant-rest/lib/api/data' {
  declare module.exports: any;
}

declare module 'losant-rest/lib/api/dataTable' {
  declare module.exports: any;
}

declare module 'losant-rest/lib/api/dataTableRow' {
  declare module.exports: any;
}

declare module 'losant-rest/lib/api/dataTableRows' {
  declare module.exports: any;
}

declare module 'losant-rest/lib/api/dataTables' {
  declare module.exports: any;
}

declare module 'losant-rest/lib/api/device' {
  declare module.exports: any;
}

declare module 'losant-rest/lib/api/deviceRecipe' {
  declare module.exports: any;
}

declare module 'losant-rest/lib/api/deviceRecipes' {
  declare module.exports: any;
}

declare module 'losant-rest/lib/api/devices' {
  declare module.exports: any;
}

declare module 'losant-rest/lib/api/edgeDeployments' {
  declare module.exports: any;
}

declare module 'losant-rest/lib/api/event' {
  declare module.exports: any;
}

declare module 'losant-rest/lib/api/events' {
  declare module.exports: any;
}

declare module 'losant-rest/lib/api/experience' {
  declare module.exports: any;
}

declare module 'losant-rest/lib/api/experienceDomain' {
  declare module.exports: any;
}

declare module 'losant-rest/lib/api/experienceDomains' {
  declare module.exports: any;
}

declare module 'losant-rest/lib/api/experienceEndpoint' {
  declare module.exports: any;
}

declare module 'losant-rest/lib/api/experienceEndpoints' {
  declare module.exports: any;
}

declare module 'losant-rest/lib/api/experienceGroup' {
  declare module.exports: any;
}

declare module 'losant-rest/lib/api/experienceGroups' {
  declare module.exports: any;
}

declare module 'losant-rest/lib/api/experienceSlug' {
  declare module.exports: any;
}

declare module 'losant-rest/lib/api/experienceSlugs' {
  declare module.exports: any;
}

declare module 'losant-rest/lib/api/experienceUser' {
  declare module.exports: any;
}

declare module 'losant-rest/lib/api/experienceUsers' {
  declare module.exports: any;
}

declare module 'losant-rest/lib/api/experienceVersion' {
  declare module.exports: any;
}

declare module 'losant-rest/lib/api/experienceVersions' {
  declare module.exports: any;
}

declare module 'losant-rest/lib/api/experienceView' {
  declare module.exports: any;
}

declare module 'losant-rest/lib/api/experienceViews' {
  declare module.exports: any;
}

declare module 'losant-rest/lib/api/file' {
  declare module.exports: any;
}

declare module 'losant-rest/lib/api/files' {
  declare module.exports: any;
}

declare module 'losant-rest/lib/api/flow' {
  declare module.exports: any;
}

declare module 'losant-rest/lib/api/flows' {
  declare module.exports: any;
}

declare module 'losant-rest/lib/api/flowVersion' {
  declare module.exports: any;
}

declare module 'losant-rest/lib/api/flowVersions' {
  declare module.exports: any;
}

declare module 'losant-rest/lib/api/index' {
  declare module.exports: any;
}

declare module 'losant-rest/lib/api/integration' {
  declare module.exports: any;
}

declare module 'losant-rest/lib/api/integrations' {
  declare module.exports: any;
}

declare module 'losant-rest/lib/api/me' {
  declare module.exports: any;
}

declare module 'losant-rest/lib/api/org' {
  declare module.exports: any;
}

declare module 'losant-rest/lib/api/orgInvites' {
  declare module.exports: any;
}

declare module 'losant-rest/lib/api/orgs' {
  declare module.exports: any;
}

declare module 'losant-rest/lib/api/solution' {
  declare module.exports: any;
}

declare module 'losant-rest/lib/api/solutions' {
  declare module.exports: any;
}

declare module 'losant-rest/lib/api/solutionUser' {
  declare module.exports: any;
}

declare module 'losant-rest/lib/api/solutionUsers' {
  declare module.exports: any;
}

declare module 'losant-rest/lib/api/webhook' {
  declare module.exports: any;
}

declare module 'losant-rest/lib/api/webhooks' {
  declare module.exports: any;
}

declare module 'losant-rest/lib/index' {
  declare module.exports: any;
}

declare module 'losant-rest/test/callback_spec' {
  declare module.exports: any;
}

declare module 'losant-rest/test/common' {
  declare module.exports: any;
}

declare module 'losant-rest/test/options_spec' {
  declare module.exports: any;
}

declare module 'losant-rest/test/promise_spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'losant-rest/examples/auth.js' {
  declare module.exports: $Exports<'losant-rest/examples/auth'>;
}
declare module 'losant-rest/examples/list_devices.js' {
  declare module.exports: $Exports<'losant-rest/examples/list_devices'>;
}
declare module 'losant-rest/lib/api/application.js' {
  declare module.exports: $Exports<'losant-rest/lib/api/application'>;
}
declare module 'losant-rest/lib/api/applicationApiToken.js' {
  declare module.exports: $Exports<'losant-rest/lib/api/applicationApiToken'>;
}
declare module 'losant-rest/lib/api/applicationApiTokens.js' {
  declare module.exports: $Exports<'losant-rest/lib/api/applicationApiTokens'>;
}
declare module 'losant-rest/lib/api/applicationKey.js' {
  declare module.exports: $Exports<'losant-rest/lib/api/applicationKey'>;
}
declare module 'losant-rest/lib/api/applicationKeys.js' {
  declare module.exports: $Exports<'losant-rest/lib/api/applicationKeys'>;
}
declare module 'losant-rest/lib/api/applications.js' {
  declare module.exports: $Exports<'losant-rest/lib/api/applications'>;
}
declare module 'losant-rest/lib/api/auditLog.js' {
  declare module.exports: $Exports<'losant-rest/lib/api/auditLog'>;
}
declare module 'losant-rest/lib/api/auditLogs.js' {
  declare module.exports: $Exports<'losant-rest/lib/api/auditLogs'>;
}
declare module 'losant-rest/lib/api/auth.js' {
  declare module.exports: $Exports<'losant-rest/lib/api/auth'>;
}
declare module 'losant-rest/lib/api/dashboard.js' {
  declare module.exports: $Exports<'losant-rest/lib/api/dashboard'>;
}
declare module 'losant-rest/lib/api/dashboards.js' {
  declare module.exports: $Exports<'losant-rest/lib/api/dashboards'>;
}
declare module 'losant-rest/lib/api/data.js' {
  declare module.exports: $Exports<'losant-rest/lib/api/data'>;
}
declare module 'losant-rest/lib/api/dataTable.js' {
  declare module.exports: $Exports<'losant-rest/lib/api/dataTable'>;
}
declare module 'losant-rest/lib/api/dataTableRow.js' {
  declare module.exports: $Exports<'losant-rest/lib/api/dataTableRow'>;
}
declare module 'losant-rest/lib/api/dataTableRows.js' {
  declare module.exports: $Exports<'losant-rest/lib/api/dataTableRows'>;
}
declare module 'losant-rest/lib/api/dataTables.js' {
  declare module.exports: $Exports<'losant-rest/lib/api/dataTables'>;
}
declare module 'losant-rest/lib/api/device.js' {
  declare module.exports: $Exports<'losant-rest/lib/api/device'>;
}
declare module 'losant-rest/lib/api/deviceRecipe.js' {
  declare module.exports: $Exports<'losant-rest/lib/api/deviceRecipe'>;
}
declare module 'losant-rest/lib/api/deviceRecipes.js' {
  declare module.exports: $Exports<'losant-rest/lib/api/deviceRecipes'>;
}
declare module 'losant-rest/lib/api/devices.js' {
  declare module.exports: $Exports<'losant-rest/lib/api/devices'>;
}
declare module 'losant-rest/lib/api/edgeDeployments.js' {
  declare module.exports: $Exports<'losant-rest/lib/api/edgeDeployments'>;
}
declare module 'losant-rest/lib/api/event.js' {
  declare module.exports: $Exports<'losant-rest/lib/api/event'>;
}
declare module 'losant-rest/lib/api/events.js' {
  declare module.exports: $Exports<'losant-rest/lib/api/events'>;
}
declare module 'losant-rest/lib/api/experience.js' {
  declare module.exports: $Exports<'losant-rest/lib/api/experience'>;
}
declare module 'losant-rest/lib/api/experienceDomain.js' {
  declare module.exports: $Exports<'losant-rest/lib/api/experienceDomain'>;
}
declare module 'losant-rest/lib/api/experienceDomains.js' {
  declare module.exports: $Exports<'losant-rest/lib/api/experienceDomains'>;
}
declare module 'losant-rest/lib/api/experienceEndpoint.js' {
  declare module.exports: $Exports<'losant-rest/lib/api/experienceEndpoint'>;
}
declare module 'losant-rest/lib/api/experienceEndpoints.js' {
  declare module.exports: $Exports<'losant-rest/lib/api/experienceEndpoints'>;
}
declare module 'losant-rest/lib/api/experienceGroup.js' {
  declare module.exports: $Exports<'losant-rest/lib/api/experienceGroup'>;
}
declare module 'losant-rest/lib/api/experienceGroups.js' {
  declare module.exports: $Exports<'losant-rest/lib/api/experienceGroups'>;
}
declare module 'losant-rest/lib/api/experienceSlug.js' {
  declare module.exports: $Exports<'losant-rest/lib/api/experienceSlug'>;
}
declare module 'losant-rest/lib/api/experienceSlugs.js' {
  declare module.exports: $Exports<'losant-rest/lib/api/experienceSlugs'>;
}
declare module 'losant-rest/lib/api/experienceUser.js' {
  declare module.exports: $Exports<'losant-rest/lib/api/experienceUser'>;
}
declare module 'losant-rest/lib/api/experienceUsers.js' {
  declare module.exports: $Exports<'losant-rest/lib/api/experienceUsers'>;
}
declare module 'losant-rest/lib/api/experienceVersion.js' {
  declare module.exports: $Exports<'losant-rest/lib/api/experienceVersion'>;
}
declare module 'losant-rest/lib/api/experienceVersions.js' {
  declare module.exports: $Exports<'losant-rest/lib/api/experienceVersions'>;
}
declare module 'losant-rest/lib/api/experienceView.js' {
  declare module.exports: $Exports<'losant-rest/lib/api/experienceView'>;
}
declare module 'losant-rest/lib/api/experienceViews.js' {
  declare module.exports: $Exports<'losant-rest/lib/api/experienceViews'>;
}
declare module 'losant-rest/lib/api/file.js' {
  declare module.exports: $Exports<'losant-rest/lib/api/file'>;
}
declare module 'losant-rest/lib/api/files.js' {
  declare module.exports: $Exports<'losant-rest/lib/api/files'>;
}
declare module 'losant-rest/lib/api/flow.js' {
  declare module.exports: $Exports<'losant-rest/lib/api/flow'>;
}
declare module 'losant-rest/lib/api/flows.js' {
  declare module.exports: $Exports<'losant-rest/lib/api/flows'>;
}
declare module 'losant-rest/lib/api/flowVersion.js' {
  declare module.exports: $Exports<'losant-rest/lib/api/flowVersion'>;
}
declare module 'losant-rest/lib/api/flowVersions.js' {
  declare module.exports: $Exports<'losant-rest/lib/api/flowVersions'>;
}
declare module 'losant-rest/lib/api/index.js' {
  declare module.exports: $Exports<'losant-rest/lib/api/index'>;
}
declare module 'losant-rest/lib/api/integration.js' {
  declare module.exports: $Exports<'losant-rest/lib/api/integration'>;
}
declare module 'losant-rest/lib/api/integrations.js' {
  declare module.exports: $Exports<'losant-rest/lib/api/integrations'>;
}
declare module 'losant-rest/lib/api/me.js' {
  declare module.exports: $Exports<'losant-rest/lib/api/me'>;
}
declare module 'losant-rest/lib/api/org.js' {
  declare module.exports: $Exports<'losant-rest/lib/api/org'>;
}
declare module 'losant-rest/lib/api/orgInvites.js' {
  declare module.exports: $Exports<'losant-rest/lib/api/orgInvites'>;
}
declare module 'losant-rest/lib/api/orgs.js' {
  declare module.exports: $Exports<'losant-rest/lib/api/orgs'>;
}
declare module 'losant-rest/lib/api/solution.js' {
  declare module.exports: $Exports<'losant-rest/lib/api/solution'>;
}
declare module 'losant-rest/lib/api/solutions.js' {
  declare module.exports: $Exports<'losant-rest/lib/api/solutions'>;
}
declare module 'losant-rest/lib/api/solutionUser.js' {
  declare module.exports: $Exports<'losant-rest/lib/api/solutionUser'>;
}
declare module 'losant-rest/lib/api/solutionUsers.js' {
  declare module.exports: $Exports<'losant-rest/lib/api/solutionUsers'>;
}
declare module 'losant-rest/lib/api/webhook.js' {
  declare module.exports: $Exports<'losant-rest/lib/api/webhook'>;
}
declare module 'losant-rest/lib/api/webhooks.js' {
  declare module.exports: $Exports<'losant-rest/lib/api/webhooks'>;
}
declare module 'losant-rest/lib/index.js' {
  declare module.exports: $Exports<'losant-rest/lib/index'>;
}
declare module 'losant-rest/test/callback_spec.js' {
  declare module.exports: $Exports<'losant-rest/test/callback_spec'>;
}
declare module 'losant-rest/test/common.js' {
  declare module.exports: $Exports<'losant-rest/test/common'>;
}
declare module 'losant-rest/test/options_spec.js' {
  declare module.exports: $Exports<'losant-rest/test/options_spec'>;
}
declare module 'losant-rest/test/promise_spec.js' {
  declare module.exports: $Exports<'losant-rest/test/promise_spec'>;
}
