// flow-typed signature: 24864854f0b5be9889a7a562d798b112
// flow-typed version: <<STUB>>/serverless-helpers_v1.0.0/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'serverless-helpers'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'serverless-helpers' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'serverless-helpers/arithmatic.example' {
  declare module.exports: any;
}

declare module 'serverless-helpers/example/example' {
  declare module.exports: any;
}

declare module 'serverless-helpers/invoke.example' {
  declare module.exports: any;
}

// Filename aliases
declare module 'serverless-helpers/arithmatic.example.js' {
  declare module.exports: $Exports<'serverless-helpers/arithmatic.example'>;
}
declare module 'serverless-helpers/example/example.js' {
  declare module.exports: $Exports<'serverless-helpers/example/example'>;
}
declare module 'serverless-helpers/index' {
  declare module.exports: $Exports<'serverless-helpers'>;
}
declare module 'serverless-helpers/index.js' {
  declare module.exports: $Exports<'serverless-helpers'>;
}
declare module 'serverless-helpers/invoke.example.js' {
  declare module.exports: $Exports<'serverless-helpers/invoke.example'>;
}
