// flow-typed signature: 8e2200d958dc4b09d556b50fc592efe1
// flow-typed version: <<STUB>>/stripe_v6.31.1/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stripe'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stripe' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'stripe/lib/autoPagination' {
  declare module.exports: any;
}

declare module 'stripe/lib/Error' {
  declare module.exports: any;
}

declare module 'stripe/lib/makeRequest' {
  declare module.exports: any;
}

declare module 'stripe/lib/MultipartDataGenerator' {
  declare module.exports: any;
}

declare module 'stripe/lib/ResourceNamespace' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/AccountLinks' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/Accounts' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/ApplePayDomains' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/ApplicationFeeRefunds' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/ApplicationFees' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/Balance' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/BitcoinReceivers' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/ChargeRefunds' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/Charges' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/Checkout/Sessions' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/CountrySpecs' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/Coupons' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/CreditNotes' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/CustomerCards' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/Customers' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/CustomerSubscriptions' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/Disputes' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/EphemeralKeys' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/Events' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/ExchangeRates' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/FileLinks' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/Files' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/InvoiceItems' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/Invoices' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/IssuerFraudRecords' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/Issuing/Authorizations' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/Issuing/Cardholders' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/Issuing/Cards' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/Issuing/Disputes' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/Issuing/Transactions' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/LoginLinks' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/OAuth' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/OrderReturns' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/Orders' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/PaymentIntents' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/PaymentMethods' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/Payouts' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/Persons' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/Plans' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/Products' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/Radar/ValueListItems' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/Radar/ValueLists' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/RecipientCards' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/Recipients' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/Refunds' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/Reporting/ReportRuns' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/Reporting/ReportTypes' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/Reviews' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/Sigma/ScheduledQueryRuns' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/SKUs' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/Sources' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/SubscriptionItems' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/Subscriptions' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/SubscriptionScheduleRevisions' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/SubscriptionSchedules' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/TaxIds' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/TaxRates' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/Terminal/ConnectionTokens' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/Terminal/Locations' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/Terminal/Readers' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/ThreeDSecure' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/Tokens' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/Topups' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/TransferReversals' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/Transfers' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/UsageRecords' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/UsageRecordSummaries' {
  declare module.exports: any;
}

declare module 'stripe/lib/resources/WebhookEndpoints' {
  declare module.exports: any;
}

declare module 'stripe/lib/stripe' {
  declare module.exports: any;
}

declare module 'stripe/lib/StripeMethod.basic' {
  declare module.exports: any;
}

declare module 'stripe/lib/StripeMethod' {
  declare module.exports: any;
}

declare module 'stripe/lib/StripeResource' {
  declare module.exports: any;
}

declare module 'stripe/lib/utils' {
  declare module.exports: any;
}

declare module 'stripe/lib/Webhooks' {
  declare module.exports: any;
}

// Filename aliases
declare module 'stripe/lib/autoPagination.js' {
  declare module.exports: $Exports<'stripe/lib/autoPagination'>;
}
declare module 'stripe/lib/Error.js' {
  declare module.exports: $Exports<'stripe/lib/Error'>;
}
declare module 'stripe/lib/makeRequest.js' {
  declare module.exports: $Exports<'stripe/lib/makeRequest'>;
}
declare module 'stripe/lib/MultipartDataGenerator.js' {
  declare module.exports: $Exports<'stripe/lib/MultipartDataGenerator'>;
}
declare module 'stripe/lib/ResourceNamespace.js' {
  declare module.exports: $Exports<'stripe/lib/ResourceNamespace'>;
}
declare module 'stripe/lib/resources/AccountLinks.js' {
  declare module.exports: $Exports<'stripe/lib/resources/AccountLinks'>;
}
declare module 'stripe/lib/resources/Accounts.js' {
  declare module.exports: $Exports<'stripe/lib/resources/Accounts'>;
}
declare module 'stripe/lib/resources/ApplePayDomains.js' {
  declare module.exports: $Exports<'stripe/lib/resources/ApplePayDomains'>;
}
declare module 'stripe/lib/resources/ApplicationFeeRefunds.js' {
  declare module.exports: $Exports<'stripe/lib/resources/ApplicationFeeRefunds'>;
}
declare module 'stripe/lib/resources/ApplicationFees.js' {
  declare module.exports: $Exports<'stripe/lib/resources/ApplicationFees'>;
}
declare module 'stripe/lib/resources/Balance.js' {
  declare module.exports: $Exports<'stripe/lib/resources/Balance'>;
}
declare module 'stripe/lib/resources/BitcoinReceivers.js' {
  declare module.exports: $Exports<'stripe/lib/resources/BitcoinReceivers'>;
}
declare module 'stripe/lib/resources/ChargeRefunds.js' {
  declare module.exports: $Exports<'stripe/lib/resources/ChargeRefunds'>;
}
declare module 'stripe/lib/resources/Charges.js' {
  declare module.exports: $Exports<'stripe/lib/resources/Charges'>;
}
declare module 'stripe/lib/resources/Checkout/Sessions.js' {
  declare module.exports: $Exports<'stripe/lib/resources/Checkout/Sessions'>;
}
declare module 'stripe/lib/resources/CountrySpecs.js' {
  declare module.exports: $Exports<'stripe/lib/resources/CountrySpecs'>;
}
declare module 'stripe/lib/resources/Coupons.js' {
  declare module.exports: $Exports<'stripe/lib/resources/Coupons'>;
}
declare module 'stripe/lib/resources/CreditNotes.js' {
  declare module.exports: $Exports<'stripe/lib/resources/CreditNotes'>;
}
declare module 'stripe/lib/resources/CustomerCards.js' {
  declare module.exports: $Exports<'stripe/lib/resources/CustomerCards'>;
}
declare module 'stripe/lib/resources/Customers.js' {
  declare module.exports: $Exports<'stripe/lib/resources/Customers'>;
}
declare module 'stripe/lib/resources/CustomerSubscriptions.js' {
  declare module.exports: $Exports<'stripe/lib/resources/CustomerSubscriptions'>;
}
declare module 'stripe/lib/resources/Disputes.js' {
  declare module.exports: $Exports<'stripe/lib/resources/Disputes'>;
}
declare module 'stripe/lib/resources/EphemeralKeys.js' {
  declare module.exports: $Exports<'stripe/lib/resources/EphemeralKeys'>;
}
declare module 'stripe/lib/resources/Events.js' {
  declare module.exports: $Exports<'stripe/lib/resources/Events'>;
}
declare module 'stripe/lib/resources/ExchangeRates.js' {
  declare module.exports: $Exports<'stripe/lib/resources/ExchangeRates'>;
}
declare module 'stripe/lib/resources/FileLinks.js' {
  declare module.exports: $Exports<'stripe/lib/resources/FileLinks'>;
}
declare module 'stripe/lib/resources/Files.js' {
  declare module.exports: $Exports<'stripe/lib/resources/Files'>;
}
declare module 'stripe/lib/resources/InvoiceItems.js' {
  declare module.exports: $Exports<'stripe/lib/resources/InvoiceItems'>;
}
declare module 'stripe/lib/resources/Invoices.js' {
  declare module.exports: $Exports<'stripe/lib/resources/Invoices'>;
}
declare module 'stripe/lib/resources/IssuerFraudRecords.js' {
  declare module.exports: $Exports<'stripe/lib/resources/IssuerFraudRecords'>;
}
declare module 'stripe/lib/resources/Issuing/Authorizations.js' {
  declare module.exports: $Exports<'stripe/lib/resources/Issuing/Authorizations'>;
}
declare module 'stripe/lib/resources/Issuing/Cardholders.js' {
  declare module.exports: $Exports<'stripe/lib/resources/Issuing/Cardholders'>;
}
declare module 'stripe/lib/resources/Issuing/Cards.js' {
  declare module.exports: $Exports<'stripe/lib/resources/Issuing/Cards'>;
}
declare module 'stripe/lib/resources/Issuing/Disputes.js' {
  declare module.exports: $Exports<'stripe/lib/resources/Issuing/Disputes'>;
}
declare module 'stripe/lib/resources/Issuing/Transactions.js' {
  declare module.exports: $Exports<'stripe/lib/resources/Issuing/Transactions'>;
}
declare module 'stripe/lib/resources/LoginLinks.js' {
  declare module.exports: $Exports<'stripe/lib/resources/LoginLinks'>;
}
declare module 'stripe/lib/resources/OAuth.js' {
  declare module.exports: $Exports<'stripe/lib/resources/OAuth'>;
}
declare module 'stripe/lib/resources/OrderReturns.js' {
  declare module.exports: $Exports<'stripe/lib/resources/OrderReturns'>;
}
declare module 'stripe/lib/resources/Orders.js' {
  declare module.exports: $Exports<'stripe/lib/resources/Orders'>;
}
declare module 'stripe/lib/resources/PaymentIntents.js' {
  declare module.exports: $Exports<'stripe/lib/resources/PaymentIntents'>;
}
declare module 'stripe/lib/resources/PaymentMethods.js' {
  declare module.exports: $Exports<'stripe/lib/resources/PaymentMethods'>;
}
declare module 'stripe/lib/resources/Payouts.js' {
  declare module.exports: $Exports<'stripe/lib/resources/Payouts'>;
}
declare module 'stripe/lib/resources/Persons.js' {
  declare module.exports: $Exports<'stripe/lib/resources/Persons'>;
}
declare module 'stripe/lib/resources/Plans.js' {
  declare module.exports: $Exports<'stripe/lib/resources/Plans'>;
}
declare module 'stripe/lib/resources/Products.js' {
  declare module.exports: $Exports<'stripe/lib/resources/Products'>;
}
declare module 'stripe/lib/resources/Radar/ValueListItems.js' {
  declare module.exports: $Exports<'stripe/lib/resources/Radar/ValueListItems'>;
}
declare module 'stripe/lib/resources/Radar/ValueLists.js' {
  declare module.exports: $Exports<'stripe/lib/resources/Radar/ValueLists'>;
}
declare module 'stripe/lib/resources/RecipientCards.js' {
  declare module.exports: $Exports<'stripe/lib/resources/RecipientCards'>;
}
declare module 'stripe/lib/resources/Recipients.js' {
  declare module.exports: $Exports<'stripe/lib/resources/Recipients'>;
}
declare module 'stripe/lib/resources/Refunds.js' {
  declare module.exports: $Exports<'stripe/lib/resources/Refunds'>;
}
declare module 'stripe/lib/resources/Reporting/ReportRuns.js' {
  declare module.exports: $Exports<'stripe/lib/resources/Reporting/ReportRuns'>;
}
declare module 'stripe/lib/resources/Reporting/ReportTypes.js' {
  declare module.exports: $Exports<'stripe/lib/resources/Reporting/ReportTypes'>;
}
declare module 'stripe/lib/resources/Reviews.js' {
  declare module.exports: $Exports<'stripe/lib/resources/Reviews'>;
}
declare module 'stripe/lib/resources/Sigma/ScheduledQueryRuns.js' {
  declare module.exports: $Exports<'stripe/lib/resources/Sigma/ScheduledQueryRuns'>;
}
declare module 'stripe/lib/resources/SKUs.js' {
  declare module.exports: $Exports<'stripe/lib/resources/SKUs'>;
}
declare module 'stripe/lib/resources/Sources.js' {
  declare module.exports: $Exports<'stripe/lib/resources/Sources'>;
}
declare module 'stripe/lib/resources/SubscriptionItems.js' {
  declare module.exports: $Exports<'stripe/lib/resources/SubscriptionItems'>;
}
declare module 'stripe/lib/resources/Subscriptions.js' {
  declare module.exports: $Exports<'stripe/lib/resources/Subscriptions'>;
}
declare module 'stripe/lib/resources/SubscriptionScheduleRevisions.js' {
  declare module.exports: $Exports<'stripe/lib/resources/SubscriptionScheduleRevisions'>;
}
declare module 'stripe/lib/resources/SubscriptionSchedules.js' {
  declare module.exports: $Exports<'stripe/lib/resources/SubscriptionSchedules'>;
}
declare module 'stripe/lib/resources/TaxIds.js' {
  declare module.exports: $Exports<'stripe/lib/resources/TaxIds'>;
}
declare module 'stripe/lib/resources/TaxRates.js' {
  declare module.exports: $Exports<'stripe/lib/resources/TaxRates'>;
}
declare module 'stripe/lib/resources/Terminal/ConnectionTokens.js' {
  declare module.exports: $Exports<'stripe/lib/resources/Terminal/ConnectionTokens'>;
}
declare module 'stripe/lib/resources/Terminal/Locations.js' {
  declare module.exports: $Exports<'stripe/lib/resources/Terminal/Locations'>;
}
declare module 'stripe/lib/resources/Terminal/Readers.js' {
  declare module.exports: $Exports<'stripe/lib/resources/Terminal/Readers'>;
}
declare module 'stripe/lib/resources/ThreeDSecure.js' {
  declare module.exports: $Exports<'stripe/lib/resources/ThreeDSecure'>;
}
declare module 'stripe/lib/resources/Tokens.js' {
  declare module.exports: $Exports<'stripe/lib/resources/Tokens'>;
}
declare module 'stripe/lib/resources/Topups.js' {
  declare module.exports: $Exports<'stripe/lib/resources/Topups'>;
}
declare module 'stripe/lib/resources/TransferReversals.js' {
  declare module.exports: $Exports<'stripe/lib/resources/TransferReversals'>;
}
declare module 'stripe/lib/resources/Transfers.js' {
  declare module.exports: $Exports<'stripe/lib/resources/Transfers'>;
}
declare module 'stripe/lib/resources/UsageRecords.js' {
  declare module.exports: $Exports<'stripe/lib/resources/UsageRecords'>;
}
declare module 'stripe/lib/resources/UsageRecordSummaries.js' {
  declare module.exports: $Exports<'stripe/lib/resources/UsageRecordSummaries'>;
}
declare module 'stripe/lib/resources/WebhookEndpoints.js' {
  declare module.exports: $Exports<'stripe/lib/resources/WebhookEndpoints'>;
}
declare module 'stripe/lib/stripe.js' {
  declare module.exports: $Exports<'stripe/lib/stripe'>;
}
declare module 'stripe/lib/StripeMethod.basic.js' {
  declare module.exports: $Exports<'stripe/lib/StripeMethod.basic'>;
}
declare module 'stripe/lib/StripeMethod.js' {
  declare module.exports: $Exports<'stripe/lib/StripeMethod'>;
}
declare module 'stripe/lib/StripeResource.js' {
  declare module.exports: $Exports<'stripe/lib/StripeResource'>;
}
declare module 'stripe/lib/utils.js' {
  declare module.exports: $Exports<'stripe/lib/utils'>;
}
declare module 'stripe/lib/Webhooks.js' {
  declare module.exports: $Exports<'stripe/lib/Webhooks'>;
}
