// flow-typed signature: 953bac979bcf7e9a2e3967ddc9121612
// flow-typed version: <<STUB>>/trello_v0.9.1/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'trello'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'trello' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'trello/main' {
  declare module.exports: any;
}

declare module 'trello/test/spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'trello/main.js' {
  declare module.exports: $Exports<'trello/main'>;
}
declare module 'trello/test/spec.js' {
  declare module.exports: $Exports<'trello/test/spec'>;
}
