# we are publishing two separate netlify sites so this 
# is configured in netlify web UI

[build]
#   # Directory to change to before starting a build. 
#   # This is where we will look for package.json/.nvmrc/etc.
#   base = "web/app/"
#   publish = "web/app/dist/"

#   # Default build command.
#   command = "npm run build"
  ignore = "git diff --quiet HEAD^ HEAD mobile/app"

[context.production.environment]
  NUXT_ENV_API_BASE = "https://api.tryclicker.com"
  NUXT_ENV_SEGMENT_KEY = "Ws6003hNu2vjLNWa8t5jmp5m3woAwH3I"
  NUXT_ENV_STRIPE_PUBLISHABLE_KEY = "pk_live_LUgXVojsYzm2R5BfCvzhYqg800QyIkTHbr"
  NUXT_ENV_CONTENTFUL_SPACE_ID = "jaxoslda9dxk"
  NUXT_ENV_CONTENTFUL_ACCESS_TOKEN = "Ai_IJR4RoCAhqsUk4q0NMXcR1ON42EHL02jD9-gjiGE"
  NUXT_ENV_STAGE = "prod"
  ENV = "production"
[context.variant.environment]
  NUXT_ENV_API_BASE = "https://api.tryclicker.com"
  NUXT_ENV_SEGMENT_KEY = "Ws6003hNu2vjLNWa8t5jmp5m3woAwH3I"
  NUXT_ENV_STRIPE_PUBLISHABLE_KEY = "pk_live_LUgXVojsYzm2R5BfCvzhYqg800QyIkTHbr"
  NUXT_ENV_CONTENTFUL_SPACE_ID = "jaxoslda9dxk"
  NUXT_ENV_CONTENTFUL_ACCESS_TOKEN = "Ai_IJR4RoCAhqsUk4q0NMXcR1ON42EHL02jD9-gjiGE"
  NUXT_ENV_STAGE = "prod"
  ENV = "production"
[context.release.environment]
  NUXT_ENV_API_BASE = "https://api-release.tryclicker.com"
  NUXT_ENV_SEGMENT_KEY="VXD6hWSRSSl5uriNd6QsBWtQEXZaMZnQ"
  NUXT_ENV_STRIPE_PUBLISHABLE_KEY = "pk_test_emgg6PM2oFAFsEmyTjomZQbG00vopAGOw7"
  NUXT_ENV_CONTENTFUL_SPACE_ID = "jaxoslda9dxk"
  NUXT_ENV_CONTENTFUL_ACCESS_TOKEN = "Ai_IJR4RoCAhqsUk4q0NMXcR1ON42EHL02jD9-gjiGE"
  NUXT_ENV_STAGE = "release"
  ENV = "release"
[context.develop.environment]
  NUXT_ENV_API_BASE = "https://api-develop.tryclicker.com"
  NUXT_ENV_SEGMENT_KEY = "VXD6hWSRSSl5uriNd6QsBWtQEXZaMZnQ"
  NUXT_ENV_STRIPE_PUBLISHABLE_KEY = "pk_test_emgg6PM2oFAFsEmyTjomZQbG00vopAGOw7"
  NUXT_ENV_CONTENTFUL_SPACE_ID = "jaxoslda9dxk"
  NUXT_ENV_CONTENTFUL_ACCESS_TOKEN = "Ai_IJR4RoCAhqsUk4q0NMXcR1ON42EHL02jD9-gjiGE"
  NUXT_ENV_STAGE = "develop"
  ENV = "develop"
[context.deploy-preview.environment]
  NUXT_ENV_API_BASE = "https://api-develop.tryclicker.com"
  NUXT_ENV_SEGMENT_KEY = "VXD6hWSRSSl5uriNd6QsBWtQEXZaMZnQ"
  NUXT_ENV_STRIPE_PUBLISHABLE_KEY = "pk_test_emgg6PM2oFAFsEmyTjomZQbG00vopAGOw7"
  NUXT_ENV_CONTENTFUL_SPACE_ID = "jaxoslda9dxk"
  NUXT_ENV_CONTENTFUL_ACCESS_TOKEN = "Ai_IJR4RoCAhqsUk4q0NMXcR1ON42EHL02jD9-gjiGE"
  ENV = "develop"
