service: serverless-api-with-dynamodb

frameworkVersion: '>=1.1.0 <2.0.0'

provider:
  name: aws
  runtime: nodejs8.10
  environment:
    tableName: ${self:custom.tableName}
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - dynamodb:*
      Resource: '*'
custom: ${file(resources/custom.yml)}
resources:
  - ${file(resources/dynamodb-table.yml)}

functions:
  create:
    handler: api/device.create
    events:
      - http:
          path: device
          method: post
          cors: true
  all:
    handler: api/device.all
    events:
      - http:
          path: device
          method: get
          cors: true
  hello:
    handler: api/device.hello
    events:
      - http:
          path: hello
          method: get
          cors: true
