service: serverless-api-with-dynamodb

frameworkVersion: '>=1.1.0 <2.0.0'

provider:
  name: aws
  runtime: nodejs8.10
  environment:
    tableName: ${self:custom.tableName}
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - dynamodb:*
      Resource: '*'
custom: ${file(resources/custom.yml)}
resources:
  - ${file(resources/dynamodb-table.yml)}

functions:
  deviceCreate:
    handler: api/device.create
    events:
      - http:
          path: device
          method: post
          cors: true
  deviceList:
    handler: api/device.list
    events:
      - http:
          path: device
          method: get
          cors: true
  deviceGet:
    handler: api/device.get
    events:
      - http:
          path: device/{losantId}
          method: get
          cors: true
          request:
            parameters:
              paths:
                losantId: true
  deviceGet:
    handler: api/device.getIp
    events:
      - http:
          path: device/{losantId}/ip
          method: get
          cors: true
          request:
            parameters:
              paths:
                losantId: true
  deviceUpdate:
    handler: api/device.update
    events:
      - http:
          path: device/{losantId}
          method: put
          cors: true
          request:
            parameters:
              paths:
                losantId: true
  deviceDelete:
    handler: api/device.delete
    events:
      - http:
          path: device/{losantId}
          method: delete
          cors: true
          request:
            parameters:
              paths:
                losantId: true
  hello:
    handler: api/device.hello
    events:
      - http:
          path: hello
          method: get
          cors: true
