# we are publishing two separate netlify sites so this 
# is configured in netlify web UI

# [build]
#   # Directory to change to before starting a build. 
#   # This is where we will look for package.json/.nvmrc/etc.
#   base = "web/app/"
#   publish = "web/app/dist/"

#   # Default build command.
#   command = "npm run build"

[context.production.environment]
  VUE_APP_API_URL = "https://api.tryclicker.com"
  VUE_APP_SEGMENT_KEY = "Ws6003hNu2vjLNWa8t5jmp5m3woAwH3I"
  ENV = "production"
[context.release.environment]
  VUE_APP_API_URL = "https://api-release.tryclicker.com"
  VUE_APP_SEGMENT_KEY="VXD6hWSRSSl5uriNd6QsBWtQEXZaMZnQ"
  ENV = "release"
[context.develop.environment]
  VUE_APP_API_URL = "https://api-develop.tryclicker.com"
  VUE_APP_SEGMENT_KEY = "VXD6hWSRSSl5uriNd6QsBWtQEXZaMZnQ"
  ENV = "develop"
[context.deploy-preview.environment]
  VUE_APP_API_URL = "https://api-develop.tryclicker.com"
  VUE_APP_SEGMENT_KEY = "VXD6hWSRSSl5uriNd6QsBWtQEXZaMZnQ"
  ENV = "develop"
