# we are publishing two separate netlify sites so this 
# is configured in netlify web UI

# [build]
#   # Directory to change to before starting a build. 
#   # This is where we will look for package.json/.nvmrc/etc.
#   base = "web/app/"
#   publish = "web/app/dist/"

#   # Default build command.
#   command = "npm run build"

[context.production.environment]
  VUE_APP_API_URL = "https://api.tryclicker.com"
  VUE_APP_SEGMENT_KEY = "Ws6003hNu2vjLNWa8t5jmp5m3woAwH3I"
  VUE_APP_STRIPE_PUBLISHABLE_KEY = "pk_live_LUgXVojsYzm2R5BfCvzhYqg800QyIkTHbr"
  VUE_APP_CONTENTFUL_SPACE_ID = "jaxoslda9dxk"
  VUE_APP_CONTENTFUL_API_TOKEN = "Ai_IJR4RoCAhqsUk4q0NMXcR1ON42EHL02jD9-gjiGE"
  ENV = "production"
[context.release.environment]
  VUE_APP_API_URL = "https://api-release.tryclicker.com"
  VUE_APP_SEGMENT_KEY="VXD6hWSRSSl5uriNd6QsBWtQEXZaMZnQ"
  VUE_APP_STRIPE_PUBLISHABLE_KEY = "pk_test_emgg6PM2oFAFsEmyTjomZQbG00vopAGOw7"
  VUE_APP_CONTENTFUL_SPACE_ID = "jaxoslda9dxk"
  VUE_APP_CONTENTFUL_API_TOKEN = "Ai_IJR4RoCAhqsUk4q0NMXcR1ON42EHL02jD9-gjiGE"
  ENV = "release"
[context.develop.environment]
  VUE_APP_API_URL = "https://api-develop.tryclicker.com"
  VUE_APP_SEGMENT_KEY = "VXD6hWSRSSl5uriNd6QsBWtQEXZaMZnQ"
  VUE_APP_STRIPE_PUBLISHABLE_KEY = "pk_test_emgg6PM2oFAFsEmyTjomZQbG00vopAGOw7"
  VUE_APP_CONTENTFUL_SPACE_ID = "jaxoslda9dxk"
  VUE_APP_CONTENTFUL_API_TOKEN = "Ai_IJR4RoCAhqsUk4q0NMXcR1ON42EHL02jD9-gjiGE"
  ENV = "develop"
[context.deploy-preview.environment]
  VUE_APP_API_URL = "https://api-develop.tryclicker.com"
  VUE_APP_SEGMENT_KEY = "VXD6hWSRSSl5uriNd6QsBWtQEXZaMZnQ"
  VUE_APP_STRIPE_PUBLISHABLE_KEY = "pk_test_emgg6PM2oFAFsEmyTjomZQbG00vopAGOw7"
  VUE_APP_CONTENTFUL_SPACE_ID = "jaxoslda9dxk"
  VUE_APP_CONTENTFUL_API_TOKEN = "Ai_IJR4RoCAhqsUk4q0NMXcR1ON42EHL02jD9-gjiGE"
  ENV = "develop"
