// flow-typed signature: fa1be60a340929b7dffca439def9c63d
// flow-typed version: <<STUB>>/dynamodb-toolbox_v0.1.0/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dynamodb-toolbox'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dynamodb-toolbox' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dynamodb-toolbox/__tests__/delete.unit.test' {
  declare module.exports: any;
}

declare module 'dynamodb-toolbox/__tests__/get.unit.test' {
  declare module.exports: any;
}

declare module 'dynamodb-toolbox/__tests__/model-creation.unit.test' {
  declare module.exports: any;
}

declare module 'dynamodb-toolbox/__tests__/models/simple-model-req' {
  declare module.exports: any;
}

declare module 'dynamodb-toolbox/__tests__/models/simple-model-sk' {
  declare module.exports: any;
}

declare module 'dynamodb-toolbox/__tests__/models/simple-model' {
  declare module.exports: any;
}

declare module 'dynamodb-toolbox/__tests__/models/test-model' {
  declare module.exports: any;
}

declare module 'dynamodb-toolbox/__tests__/parse.unit.test' {
  declare module.exports: any;
}

declare module 'dynamodb-toolbox/__tests__/put.unit.test' {
  declare module.exports: any;
}

declare module 'dynamodb-toolbox/__tests__/update.unit.test' {
  declare module.exports: any;
}

declare module 'dynamodb-toolbox/__tests__/utility.unit.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dynamodb-toolbox/__tests__/delete.unit.test.js' {
  declare module.exports: $Exports<'dynamodb-toolbox/__tests__/delete.unit.test'>;
}
declare module 'dynamodb-toolbox/__tests__/get.unit.test.js' {
  declare module.exports: $Exports<'dynamodb-toolbox/__tests__/get.unit.test'>;
}
declare module 'dynamodb-toolbox/__tests__/model-creation.unit.test.js' {
  declare module.exports: $Exports<'dynamodb-toolbox/__tests__/model-creation.unit.test'>;
}
declare module 'dynamodb-toolbox/__tests__/models/simple-model-req.js' {
  declare module.exports: $Exports<'dynamodb-toolbox/__tests__/models/simple-model-req'>;
}
declare module 'dynamodb-toolbox/__tests__/models/simple-model-sk.js' {
  declare module.exports: $Exports<'dynamodb-toolbox/__tests__/models/simple-model-sk'>;
}
declare module 'dynamodb-toolbox/__tests__/models/simple-model.js' {
  declare module.exports: $Exports<'dynamodb-toolbox/__tests__/models/simple-model'>;
}
declare module 'dynamodb-toolbox/__tests__/models/test-model.js' {
  declare module.exports: $Exports<'dynamodb-toolbox/__tests__/models/test-model'>;
}
declare module 'dynamodb-toolbox/__tests__/parse.unit.test.js' {
  declare module.exports: $Exports<'dynamodb-toolbox/__tests__/parse.unit.test'>;
}
declare module 'dynamodb-toolbox/__tests__/put.unit.test.js' {
  declare module.exports: $Exports<'dynamodb-toolbox/__tests__/put.unit.test'>;
}
declare module 'dynamodb-toolbox/__tests__/update.unit.test.js' {
  declare module.exports: $Exports<'dynamodb-toolbox/__tests__/update.unit.test'>;
}
declare module 'dynamodb-toolbox/__tests__/utility.unit.test.js' {
  declare module.exports: $Exports<'dynamodb-toolbox/__tests__/utility.unit.test'>;
}
declare module 'dynamodb-toolbox/index' {
  declare module.exports: $Exports<'dynamodb-toolbox'>;
}
declare module 'dynamodb-toolbox/index.js' {
  declare module.exports: $Exports<'dynamodb-toolbox'>;
}
