service: box
frameworkVersion: '>=1.0.0 <2.0.0'
provider:
  name: aws
  memorySize: 1024
  versionFunctions: false
  runtime: nodejs12.x
  # tracing: true
  logRetentionInDays: 14
  deploymentBucket:
    name: serverless-deploys-clicker
  environment:
    stage: ${self:custom.stage}
    region: ${opt:region, self:provider.region}
  iamRoleStatements: ${file(../serverless.common.yml):iamRoleStatements}
plugins:
  - serverless-prune-plugin
  - serverless-deployment-bucket
  - serverless-domain-manager
  - serverless-sentry
  - serverless-dotenv-plugin
  - serverless-plugin-tracing
  - serverless-bundle
custom:
  stage: ${opt:stage}
  bundle:
    sourcemaps: false
    linting: false
  prune:
    automatic: true
    number: 3
  domains: ${file(../serverless.common.yml):domains}
  customDomain:
    domainName: ${self:custom.domains.${self:custom.stage}}
    basePath: boxes
    certificateName: 'api.tryclicker.com'
    stage: ${self:custom.stage}
    createRoute53Record: true
    endpointType: 'edge'
  sentry:
    dsn: ${env:SENTRY_DSN_ENDPOINT}
  dotenv:
    basePath: ../
functions:
  health:
    handler: box.health
    events:
      - http:
          path: health
          method: get
  createDirectv:
    handler: box.createDirectv
    timeout: 12
    events:
      - http:
          path: '{locationId}/directv'
          method: post
  create:
    handler: box.create
    timeout: 12
    events:
      - http:
          path: '{locationId}'
          method: post
  updateLive:
    handler: box.updateLive
    events:
      - http:
          path: '{locationId}/{boxId}/live'
          method: put
  remove:
    handler: box.remove
    events:
      - http:
          path: '{locationId}/{boxId}'
          method: delete
  get:
    handler: box.get
    events:
      - http:
          path: '{locationId}/{boxId}'
          method: get
  getAll:
    timeout: 12
    handler: box.getAll
    events:
      - http:
          path: '{locationId}'
          method: get
