version: 2.1
jobs:
  build:
    branches:
      only:
        - master
        - stage
        - develop
    docker:
      - image: circleci/node:8.10
    working_directory: ~/captain/functions/widget
    #     steps:
    #       - serverlessci

    # commands:
    #   serverlessci:
    # description: 'CI steps for building, testing, deploying serverless functions'
    # parameters:
    #   to:
    #     type: string
    #     default: 'Hello World'
    steps:
      - checkout:
          path: ~/captain
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo npm i -g serverless
            npm i
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run tests
          command: npm test
      - run:
          name: Deploy application
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              npm run deploy:prod
            fi
            if [ "${CIRCLE_BRANCH}" == "stage" ]; then
              npm run deploy:stage
            fi
            if [ "${CIRCLE_BRANCH}" == "develop" ]; then
              npm run deploy:develop
            fi
