defaults: &defaults
  steps:
    - checkout:
        path: ~/captain
    - restore_cache:
        key: dependency-cache-{{ checksum "package.json" }}
    - run:
        name: install dependencies
        command: |
          npm i
    - save_cache: # special step to save the dependency cache
        key: dependency-cache-{{ checksum "package.json" }}
        paths:
          - ./node_modules
    - run:
        name: run tests
        command: npm test
    - run:
        name: deploy functions
        command: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            npx serverless deploy --verbose --stage prod
          fi
          if [ "${CIRCLE_BRANCH}" == "stage" ]; then
            npx serverless deploy --verbose --stage stage
          fi
          if [ "${CIRCLE_BRANCH}" == "develop" ]; then
            echo $PWD
            echo "$AWS_ACCESS_KEY_ID"
            echo "$AWS_SECRET_ACCESS_KEY"
            npx serverless --version
            npx serverless deploy --stage develop -v
          fi

version: 2.0
jobs:
  build:
    branches:
      only:
        - master
        - stage
        - develop
    docker:
      - image: circleci/node:8.10
    working_directory: ~/captain/functions/widget
    <<: *defaults
