defaults: &defaults
  docker:
    - image: circleci/node:8.10
  steps:
    - checkout:
        path: ~/captain
    - restore_cache:
        key: dependency-cache-{{ checksum "package.json" }}
    - run:
        name: Install dependencies
        command: npm i
    - save_cache:
        key: dependency-cache-{{ checksum "package.json" }}
        paths:
          - ./node_modules
    - run:
        name: Run tests
        command: npm test
    - run:
        name: Deploy application
        branches:
          only:
            - master
            - stage
            - develop
        command: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            npx serverless deploy --stage prod --verbose
          fi
          if [ "${CIRCLE_BRANCH}" == "stage" ]; then
            npx serverless deploy --stage stage --verbose
          fi
          if [ "${CIRCLE_BRANCH}" == "develop" ]; then
            npx serverless deploy --stage dev --verbose
          fi

version: 2.0
jobs:
  build-widget:
    working_directory: ~/captain/functions/widget
    <<: *defaults
  build-lead:
    working_directory: ~/captain/functions/lead
    <<: *defaults

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-widget
      - build-lead
