version: 2.1

parameters:
  trigger:
    type: boolean
    default: true

  functionslead:
    type: boolean
    default: false

executors:
  node:
    docker:
      - image: circleci/node

jobs:
  trigger-workflows:
    # docker:
    #   - image: circleci/node:8.10
    executor: node
    steps:
      - checkout
      - run:
          name: Determine which projects have changed and trigger the builds
          # command: chmod +x .circleci/circle_trigger.sh && .circleci/circle_trigger.sh
          command: node .circleci/circle_trigger.js
  serverless-build-test-deploy:
    parameters:
      package_name:
        type: string
    working_directory: ~/<< parameters.package_name >>
    docker:
      - image: nikolaik/python-nodejs
    steps:
      - checkout:
          path: ~/clicker
      - restore_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm i
      - save_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run tests
          command: npm test
      - run:
          name: Deploy serverless function
          branches:
            only:
              - master
              - release
              - develop
          command: |
            npm run build --if-present
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              npx serverless deploy --stage prod --verbose
            fi
            if [ "${CIRCLE_BRANCH}" == "release" ]; then
              npx serverless deploy --stage release --verbose
            fi
            if [ "${CIRCLE_BRANCH}" == "develop" ]; then
              npx serverless deploy --stage develop --verbose
            fi

workflows:
  version: 2
  ci:
    when: << pipeline.parameters.trigger >>
    jobs:
      - trigger-workflows:
        filters:
          branches:
            only:
              - master
              - release
              - develop
  functionslead:
    when: << pipeline.parameters.functionslead >>
    # working_directory: ~/clicker/functions/lead
    jobs:
      - serverless-build-test-deploy:
          # name: serverless-build-test-deploy
          package_name: functions/lead
        # <<: *serverless_build_test_deploy
  # functions/admin:
  #   working_directory: ~/clicker/functions/admin
  #   <<: *serverless_build_test_deploy
  # functions/analytics:
  #   working_directory: ~/clicker/functions/analytics
  #   <<: *serverless_build_test_deploy
  # functions/app:
  #   working_directory: ~/clicker/functions/app
  #   <<: *serverless_build_test_deploy
  # functions/game:
  #   working_directory: ~/clicker/functions/game
  #   <<: *serverless_build_test_deploy
  # functions/job:
  #   working_directory: ~/clicker/functions/job
  #   <<: *serverless_build_test_deploy
  # functions/location:
  #   working_directory: ~/clicker/functions/location
  #   <<: *serverless_build_test_deploy
  # functions/notification:
  #   working_directory: ~/clicker/functions/notification
  #   <<: *serverless_build_test_deploy
  # functions/program:
  #   working_directory: ~/clicker/functions/program
  #   <<: *serverless_build_test_deploy
  # functions/receiver:
  #   working_directory: ~/clicker/functions/receiver
  #   <<: *serverless_build_test_deploy
  # functions/remote:
  #   working_directory: ~/clicker/functions/remote
  #   <<: *serverless_build_test_deploy
  # functions/reservation:
  #   working_directory: ~/clicker/functions/reservation
  #   <<: *serverless_build_test_deploy
  # functions/user:
  #   working_directory: ~/clicker/functions/user
  #   <<: *serverless_build_test_deploy
  # functions/widget:
  #   working_directory: ~/clicker/functions/widget
  #   <<: *serverless_build_test_deploy
  # web/app:
  #   working_directory: ~/clicker/web/app
  #   docker:
  #     - image: circleci/node:8.10
  #   steps:
  #     - run:
  #         name: Trigger Netlify build + deploy
  #         branches:
  #           only:
  #             - master
  #             - release
  #             - develop
  #         command: |
  #           echo -e "deploy clicker web"
  #           if [ "${CIRCLE_BRANCH}" == "master" ]; then
  #             curl -X POST -d {} https://api.netlify.com/build_hooks/5c7458709c6a819dd611ee82
  #           fi
  #           if [ "${CIRCLE_BRANCH}" == "release" ]; then
  #             curl -X POST -d {} https://api.netlify.com/build_hooks/5c74588dce2aff6b7eb9d135
  #           fi
  #           if [ "${CIRCLE_BRANCH}" == "develop" ]; then
  #             curl -X POST -d {} https://api.netlify.com/build_hooks/5c745884ad8fd5e199de18cf
  #           fi
  # mobile/app:
  #   working_directory: ~/clicker/mobile/app
  #   docker:
  #     - image: circleci/node:8.10
  #   steps:
  #     - run:
  #         name: Trigger Netlify build + deploy
  #         branches:
  #           only:
  #             - master
  #             - release
  #             - develop
  #         command: |
  #           echo -e "deploy clicker mobile"
  #           if [ "${CIRCLE_BRANCH}" == "master" ]; then
  #             curl -X POST -d {} https://api.netlify.com/build_hooks/5c745a22aad21db652db51e1
  #           fi
  #           if [ "${CIRCLE_BRANCH}" == "release" ]; then
  #             curl -X POST -d {} https://api.netlify.com/build_hooks/5c745a2933754a346bf8ef90
  #           fi
  #           if [ "${CIRCLE_BRANCH}" == "develop" ]; then
  #             curl -X POST -d {} https://api.netlify.com/build_hooks/5c745a2f1056ec16dab4338b
  #           fi
  # packages/antenna:
  #   working_directory: ~/clicker/packages/antenna
  #   docker:
  #     - image: chybie/node-aws-cli
  #   steps:
  #     - checkout:
  #         path: ~/clicker
  #     - run:
  #         name: Install dependencies
  #         command: npm i
  #     - run:
  #         name: Upload app zip to s3
  #         branches:
  #           only:
  #             - master
  #             - release
  #             - develop
  #         command: |
  #           echo -e "upload antenna package to s3"
  #           filename=
  #           if [ "${CIRCLE_BRANCH}" == "master" ]; then
  #             filename="antenna.tar.gz"
  #           fi
  #           if [ "${CIRCLE_BRANCH}" == "release" ]; then
  #             filename="antenna-release.tar.gz"
  #           fi
  #           if [ "${CIRCLE_BRANCH}" == "develop" ]; then
  #             filename="antenna-develop.tar.gz"
  #           fi
  #           tar zcvf $filename *
  #           aws s3 cp $filename s3://clicker-antenna/app/
  # e2e/app:
  #   working_directory: ~/clicker/e2e/app
  #   docker:
  #     - image: cypress/base:10
  #   steps:
  #     - checkout:
  #         path: ~/clicker
  #     # - restore_cache:
  #     #     key: dependency-cache-{{ checksum "package.json" }}
  #     # - restore_cache:
  #     #     key: cypress
  #     - restore_cache:
  #         keys:
  #           - v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
  #           # - v1-deps-{{ .Branch }}
  #           # - v1-deps
  #     - run:
  #         name: Install dependencies
  #         command: npm ci
  #     - save_cache:
  #         key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
  #         # cache NPM modules and the folder with the Cypress binary
  #         paths:
  #           - ~/.cache
  #           - ./node_modules
  #     # - save_cache:
  #     #     key: dependency-cache-{{ checksum "package.json" }}
  #     #     paths:
  #     #       - ./node_modules
  #     # - save_cache:
  #     #     key: cypress
  #     #     paths:
  #     #       - /root/.cache/Cypress/3.4.1/Cypress
  #     - run:
  #         name: Run e2e tests
  #         no_output_timeout: 3m
  #         branches:
  #           only:
  #             - master
  #             - release
  #             - develop
  #         command: |
  #           npm run test:ci
