defaults: &defaults
  steps:
    - checkout:
        path: ~/captain
    - restore_cache:
        key: dependency-cache-{{ checksum "package.json" }}
    - run:
        name: Install dependencies
        command: npm i
    - save_cache: # special step to save the dependency cache
        key: dependency-cache-{{ checksum "package.json" }}
        paths:
          - ./node_modules
    - run:
        name: Run tests
        command: npm test
    - run:
        name: Deploy application
        command: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            npx serverless deploy --stage prod --verbose
          fi
          if [ "${CIRCLE_BRANCH}" == "stage" ]; then
            npx serverless deploy --stage stage --verbose
          fi
          if [ "${CIRCLE_BRANCH}" == "develop" ]; then
            npx serverless deploy --stage dev --verbose
          fi

version: 2.0
jobs:
  build_widget:
    branches:
      only:
        - master
        - stage
        - develop
    docker:
      - image: circleci/node:8.10
    working_directory: ~/captain/functions/widget
    <<: *defaults
  build_lead:
    branches:
      only:
        - master
        - stage
        - develop
    docker:
      - image: circleci/node:8.10
    working_directory: ~/captain/functions/lead
    <<: *defaults

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build_widget
      - build_lead
