defaults: &defaults
  steps:
    - checkout:
        path: ~/captain
    - restore_cache:
        key: dependency-cache-{{ checksum "package.json" }}
    - run:
        name: Install Serverless CLI and dependencies
        command: |
          npm i
    - save_cache: # special step to save the dependency cache
        key: dependency-cache-{{ checksum "package.json" }}
        paths:
          - ./node_modules
    - run:
        name: Run tests
        command: npm test
    - run:
        name: Deploy application
        command: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            serverless deploy --stage prod -v
          fi
          if [ "${CIRCLE_BRANCH}" == "stage" ]; then
            serverless deploy --stage stage -v
          fi
          if [ "${CIRCLE_BRANCH}" == "develop" ]; then
            echo "$AWS_ACCESS_KEY_ID"
            echo "$AWS_SECRET_ACCESS_KEY"
            npx serverless --version
            npx serverless deploy --verbose --stage develop
          fi

version: 2.0
jobs:
  build:
    branches:
      only:
        - master
        - stage
        - develop
    docker:
      - image: circleci/node:8.10
    working_directory: ~/captain/functions/widget
    #     steps:
    #       - serverlessci

    # commands:
    #   serverlessci:
    # description: 'CI steps for building, testing, deploying serverless functions'
    # parameters:
    #   to:
    #     type: string
    #     default: 'Hello World'
    <<: *defaults
