aliases:
  - &serverless_build_test_deploy
    docker:
      # - image: circleci/node:8.10
      # - image: circleci/python:3.8.1
      - image: nikolaik/python-nodejs
    steps:
      - checkout:
          path: ~/clicker
      - restore_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm i
      - save_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run tests
          command: npm test
      - run:
          name: Deploy serverless function
          branches:
            only:
              - master
              - release
              - develop
          command: |
            npm run build --if-present
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              npx serverless deploy --stage prod --verbose
            fi
            if [ "${CIRCLE_BRANCH}" == "release" ]; then
              npx serverless deploy --stage release --verbose
            fi
            if [ "${CIRCLE_BRANCH}" == "develop" ]; then
              npx serverless deploy --stage develop --verbose
            fi

version: 2.1

parameters:
  # By default we enable the main workflow
  trigger:
    type: boolean
    default: true

  # Add a boolean parameter on each package.
  package1:
    type: boolean
    default: false

executors:
  node:
    docker:
      - image: circleci/node

jobs:
  trigger-workflows:
    executor: node
    steps:
      - checkout
      - run: yarn --frozen-lockfile
      - run:
          name: Trigger workflows
          command: node ./circleci.js

  lint:
    parameters:
      package_name:
        type: string
    executor: node
    steps:
      - run:
          name: Running linter on << parameters.package_name >>
          command: echo << parameters.package_name >> lint

  test:
    parameters:
      package_name:
        type: string
    executor: node
    steps:
      - run:
          name: Running linter on << parameters.package_name >>
          command: echo << parameters.package_name >> lint

workflows:
  version: 2

  # The main workflow will trigger other workflow based on your changes
  trigger:
    when: << pipeline.parameters.trigger >>
    jobs:
      - trigger-workflows
      # - new_version:
      #     requires:
      #       - trigger-workflows
      #     filters:
      #       branches:
      #         only:
      #           - master

  # Workflows defined for each package.
  package1:
    when: << pipeline.parameters.package1 >>
    jobs:
      functions/location:
        working_directory: ~/clicker/functions/location
        <<: *serverless_build_test_deploy
