service: receiver
frameworkVersion: '>=1.1.0 <2.0.0'
provider:
  name: aws
  runtime: nodejs8.10
  environment:
    stage: ${self:custom.stage}

plugins:
  - serverless-domain-manager

custom:
  stage: ${opt:stage, self:provider.stage}
  domains:
    prod: api.tryclicker.com
    release: api-release.tryclicker.com
    dev: api-dev.tryclicker.com
  customDomain:
    domainName: ${self:custom.domains.${self:custom.stage}}
    basePath: receivers
    certificateName: 'api.tryclicker.com'
    stage: ${self:custom.stage}
    createRoute53Record: true
    endpointType: 'edge'

functions:
  health:
    handler: receiver.health
    events:
      - http:
          path: health
          method: get
          cors: true
  get:
    handler: receiver.getBoxes
    events:
      - http:
          path: '{id}/boxes'
          method: get
          cors: true
  register:
    handler: receiver.register
    events:
      - http:
          path: '{id}'
          method: put
          cors: true
  setIp:
    handler: receiver.setIp
    events:
      - http:
          path: '{id}/ip'
          method: put
          cors: true
  setBoxes:
    handler: receiver.setBoxes
    events:
      - http:
          path: '{id}/boxes'
          method: put
          cors: true
  setTags:
    handler: receiver.setTags
    events:
      - http:
          path: '{id}/boxes/tags'
          method: put
          cors: true
  identify:
    handler: receiver.identify
    events:
      - http:
          path: '{id}/identify'
          method: post
          cors: true
