service: program
frameworkVersion: '>=1.1.0 <2.0.0'
provider:
  name: aws
  memorySize: 128
  versionFunctions: false
  runtime: nodejs10.x
  tracing: true
  deploymentBucket:
    name: serverless-deploys-clicker
  environment:
    stage: ${self:custom.stage}
    tableProgram: ${self:custom.tableProgram}
    serviceName: ${self:service}
    airtableKey: ${env:AIRTABLE_KEY}
    airtableBase: ${self:custom.airtableBase.${self:custom.stage}}
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - dynamodb:*
        - lambda:InvokeFunction
        - lambda:InvokeAsync
        - xray:PutTraceSegments
        - xray:PutTelemetryRecords
      Resource: '*'
    - Effect: Allow
      Action:
        - SNS:Publish
      Resource:
        {
          'Fn::Join':
            [
              '',
              ['arn:aws:sns:${self:provider.region}:', { 'Ref': 'AWS::AccountId' }, ':${self:custom.newProgramTopic}'],
            ],
        }
    - Effect: Allow
      Action:
        - SNS:Publish
      Resource:
        {
          'Fn::Join':
            [
              '',
              [
                'arn:aws:sns:${self:provider.region}:',
                { 'Ref': 'AWS::AccountId' },
                ':${self:custom.newProgramAirtableTopic}',
              ],
            ],
        }

plugins:
  - serverless-domain-manager
  - serverless-prune-plugin
  - serverless-sentry
  - serverless-dotenv-plugin
  - serverless-plugin-tracing

custom:
  stage: ${opt:stage, self:provider.stage}
  prune:
    automatic: true
    number: 3
  tableProgram: programs-${self:custom.stage}
  domains:
    prod: api.tryclicker.com
    release: api-release.tryclicker.com
    develop: api-develop.tryclicker.com
  airtableBase:
    prod: ${env:AIRTABLE_BASE}
    release: ${env:AIRTABLE_BASE_RELEASE}
    develop: ${env:AIRTABLE_BASE_DEV}
  customDomain:
    domainName: ${self:custom.domains.${self:custom.stage}}
    basePath: programs
    certificateName: 'api.tryclicker.com'
    stage: ${self:custom.stage}
    createRoute53Record: true
    endpointType: 'edge'
  sentry:
    dsn: ${env:SENTRY_DSN_ENDPOINT}
  dotenv:
    basePath: ../
  newProgramTopic: ${self:service}-${self:custom.stage}-new-program-topic
  newProgramTopicArn:
    deployed:
      {
        'Fn::Join':
          [
            '',
            ['arn:aws:sns:${self:provider.region}:', { 'Ref': 'AWS::AccountId' }, ':${self:custom.newProgramTopic}'],
          ],
      }
  newProgramAirtableTopic: ${self:service}-${self:custom.stage}-new-program-airtable-topic
  newProgramAirtableTopicArn:
    deployed:
      {
        'Fn::Join':
          [
            '',
            [
              'arn:aws:sns:${self:provider.region}:',
              { 'Ref': 'AWS::AccountId' },
              ':${self:custom.newProgramAirtableTopic}',
            ],
          ],
      }
resources:
  Resources:
    newProgramTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ${self:service}-${self:custom.stage}-new-program-topic
        # TopicName: ${self:custom.newProgramTopic}
    newProgramQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:service}-${self:custom.stage}-new-program-queue
        RedrivePolicy:
          deadLetterTargetArn: !GetAtt
            - newProgramDLQ
            - Arn
          maxReceiveCount: 3
    newProgramDLQ:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:service}-${self:custom.stage}-new-program-queue-dlq
    snsToNewProgramQueueSqsPolicy:
      Type: AWS::SQS::QueuePolicy
      Properties:
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Sid: 'allow-sns-messages'
              Effect: Allow
              Principal: '*'
              Resource: !GetAtt
                - newProgramQueue
                - Arn
              Action: 'SQS:SendMessage'
              Condition:
                ArnEquals:
                  'aws:SourceArn': !Ref newProgramTopic
        Queues:
          - Ref: newProgramQueue
    newProgramQueueSubscription:
      Type: 'AWS::SNS::Subscription'
      Properties:
        TopicArn: !Ref newProgramTopic
        Endpoint: !GetAtt
          - newProgramQueue
          - Arn
        Protocol: sqs
        RawMessageDelivery: 'true'
    newProgramAirtableTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ${self:service}-${self:custom.stage}-new-program-airtable-topic
        # TopicName: ${self:custom.newProgramAirtableTopic}
    newProgramAirtableQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:service}-${self:custom.stage}-new-program-airtable-queue
        RedrivePolicy:
          deadLetterTargetArn: !GetAtt
            - newProgramAirtableDLQ
            - Arn
          maxReceiveCount: 3
    newProgramAirtableDLQ:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:service}-${self:custom.stage}-new-program-airtable-queue-dlq
    snsToNewProgramAirtableQueueSqsPolicy:
      Type: AWS::SQS::QueuePolicy
      Properties:
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Sid: 'allow-sns-messages'
              Effect: Allow
              Principal: '*'
              Resource: !GetAtt
                - newProgramAirtableQueue
                - Arn
              Action: 'SQS:SendMessage'
              Condition:
                ArnEquals:
                  'aws:SourceArn': !Ref newProgramAirtableTopic
        Queues:
          - Ref: newProgramAirtableQueue
    newProgramAirtableQueueSubscription:
      Type: 'AWS::SNS::Subscription'
      Properties:
        TopicArn: !Ref newProgramAirtableTopic
        Endpoint: !GetAtt
          - newProgramAirtableQueue
          - Arn
        Protocol: sqs
        RawMessageDelivery: 'true'
    ProgramTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: ${self:custom.tableProgram}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: region
            AttributeType: S
          - AttributeName: start
            AttributeType: N
          - AttributeName: id
            AttributeType: S
          - AttributeName: programmingId
            AttributeType: S
        KeySchema:
          - AttributeName: region
            KeyType: HASH
          - AttributeName: id
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: programmingIdGlobalIndex
            KeySchema:
              - AttributeName: programmingId
                KeyType: HASH
            Projection:
              ProjectionType: KEYS_ONLY
            # ProvisionedThroughput:
        LocalSecondaryIndexes:
          - IndexName: startLocalIndex
            KeySchema:
              - AttributeName: region
                KeyType: HASH
              - AttributeName: start
                KeyType: RANGE
            Projection:
              NonKeyAttributes:
                - id
              ProjectionType: INCLUDE
functions:
  health:
    handler: program.health
    events:
      - http:
          path: health
          method: get
          cors:
            origin: '*'
            headers:
              - partner
              - authorization
              - content-type
  getAll:
    handler: program.getAll
    memorySize: 1024
    timeout: 20
    events:
      - http:
          path: 'location/{locationId}'
          method: get
          cors:
            origin: '*'
            headers:
              - partner
              - authorization
              - content-type
  syncRegions:
    handler: program.syncRegions
    # timeout: 60
    events:
      - schedule: rate(2 hours)
      # - schedule: rate(60 minutes)
      # - schedule: cron(0 5 * * ? *) # every day @ 1am eastern
      # - schedule: cron(0 13 * * ? *) # every day @ 9am eastern
      # - schedule: cron(0 21 * * ? *) # every day @ 5pm eastern
      - http:
          path: 'sync'
          method: post
          cors:
            origin: '*'
            headers:
              - partner
              - authorization
              - content-type
  syncRegionNextFewHours:
    handler: program.syncRegionNextFewHours
    memorySize: 1024
    timeout: 60
    environment:
      # newProgramTopicArn: ${self:custom.newProgramTopicArn.${self:provider.stage}}
      newProgramTopicArn: ${self:custom.newProgramTopicArn.deployed}
  syncAirtable:
    handler: program.syncAirtable
    memorySize: 1024
    timeout: 60
    environment:
      newProgramAirtableTopicArn: ${self:custom.newProgramAirtableTopicArn.deployed}
    events:
      - schedule: cron(10 10 * * ? *) # every day @ 6:10am eastern
      - http:
          path: sync/airtable
          method: post
          cors:
            origin: '*'
            headers:
              - partner
              - authorization
              - content-type
  syncAirtableUpdates:
    handler: program.syncAirtableUpdates
    events:
      - schedule: rate(5 minutes)
      - http:
          path: sync/airtable/updates
          method: post
          cors:
            origin: '*'
            headers:
              - partner
              - authorization
              - content-type
  consumeNewProgramUpdateDetails:
    memorySize: 512
    timeout: 12
    handler: program.consumeNewProgramUpdateDetails
    description: Consume new db program and update description
    reservedConcurrency: 1
    events:
      - sqs:
          arn: !GetAtt
            - newProgramQueue
            - Arn
          batchSize: 1
  consumeNewProgramAirtableUpdateDetails:
    handler: program.consumeNewProgramAirtableUpdateDetails
    description: Consume new airtable program update description
    reservedConcurrency: 1
    events:
      - sqs:
          arn: !GetAtt
            - newProgramAirtableQueue
            - Arn
          batchSize: 1
