service: programs
frameworkVersion: '>=1.1.0 <2.0.0'
provider:
  name: aws
  memorySize: 128
  versionFunctions: false
  runtime: nodejs10.x
  tracing: true
  deploymentBucket:
    name: serverless-deploys-clicker
  environment: 
    stage: ${self:custom.stage}
    tableProgram: ${self:custom.tableProgram}
    serviceName: ${self:service}
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - dynamodb:*
        - lambda:InvokeFunction
        - lambda:InvokeAsync
        - xray:PutTraceSegments
        - xray:PutTelemetryRecords
      Resource: '*'
    - Effect: Allow
      Action:
        - SNS:Publish
      Resource:
        {
          'Fn::Join':
            [
              '',
              ['arn:aws:sns:${self:provider.region}:', { 'Ref': 'AWS::AccountId' }, ':${self:custom.newProgramTopic}'],
            ],
        }

plugins:
  - serverless-domain-manager
  - serverless-prune-plugin
  - serverless-sentry
  - serverless-dotenv-plugin
  - serverless-plugin-tracing

custom:
  stage: ${opt:stage, self:provider.stage}
  prune:
    automatic: true
    number: 3
  tableProgram: programs-${self:custom.stage}
  tableThroughputs:
    prod: 5
    default: 1
  tableThroughput: ${self:custom.tableThroughputs.${self:custom.stage}, self:custom.tableThroughputs.default}
  domains:
    prod: api.tryclicker.com
    release: api-release.tryclicker.com
    develop: api-develop.tryclicker.com
  customDomain:
    domainName: ${self:custom.domains.${self:custom.stage}}
    basePath: programs
    certificateName: 'api.tryclicker.com'
    stage: ${self:custom.stage}
    createRoute53Record: true
    endpointType: 'edge'
  sentry:
    dsn: ${env:SENTRY_DSN_ENDPOINT}
  dotenv:
    basePath: ../
  newProgramTopic: '${self:service}-${self:custom.stage}-new-program-topic'
  newProgramTopicArn:
    #   # local:
    #   #   "arn:aws:sns:us-east-1:123456789012:${self:custom.newProgramTopic}"
    deployed:
      {
        'Fn::Join':
          [
            '',
            ['arn:aws:sns:${self:provider.region}:', { 'Ref': 'AWS::AccountId' }, ':${self:custom.newProgramTopic}'],
          ],
      }
resources:
  Resources:
    newProgramTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ${self:service}-${self:custom.stage}-new-program-topic
    newProgramQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:service}-${self:custom.stage}-new-program-queue
        RedrivePolicy:
          deadLetterTargetArn: !GetAtt
            - newProgramDLQ
            - Arn
          maxReceiveCount: 3
    newProgramDLQ:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:service}-${self:custom.stage}-new-program-queue-dlq
    snsToNewProgramQueueSqsPolicy:
      Type: AWS::SQS::QueuePolicy
      Properties:
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Sid: 'allow-sns-messages'
              Effect: Allow
              Principal: '*'
              Resource: !GetAtt
                - newProgramQueue
                - Arn
              Action: 'SQS:SendMessage'
              Condition:
                ArnEquals:
                  'aws:SourceArn': !Ref newProgramTopic
        Queues:
          - Ref: newProgramQueue
    newProgramQueueSubscription:
      Type: 'AWS::SNS::Subscription'
      Properties:
        TopicArn: !Ref newProgramTopic
        Endpoint: !GetAtt
          - newProgramQueue
          - Arn
        Protocol: sqs
        RawMessageDelivery: 'true'
    ProgramTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: ${self:custom.tableProgram}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: region
            AttributeType: S
          - AttributeName: start
            AttributeType: N
          # - AttributeName: end
          #   AttributeType: N
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: region
            KeyType: HASH
          - AttributeName: id
            KeyType: RANGE
        LocalSecondaryIndexes:
          - IndexName: startLocalIndex
            KeySchema:
              - AttributeName: region
                KeyType: HASH
              - AttributeName: start
                KeyType: RANGE
            Projection:
              ProjectionType: KEYS_ONLY
        #   - IndexName: endLocalIndex
        #     KeySchema:
        #       - AttributeName: region
        #         KeyType: HASH
        #       - AttributeName: end
        #         KeyType: RANGE
        #     Projection:
        #       ProjectionType: KEYS_ONLY
        # GlobalSecondaryIndexes:
        #   - IndexName: regionGlobalIndex
        #     KeySchema:
        #       - AttributeName: region
        #         KeyType: HASH
        #     Projection:
        #       ProjectionType: ALL
        #     ProvisionedThroughput:
        #       ReadCapacityUnits: ${self:custom.tableThroughput}
        #       WriteCapacityUnits: ${self:custom.tableThroughput}
        # ProvisionedThroughput:
        #   ReadCapacityUnits: ${self:custom.tableThroughput}
        #   WriteCapacityUnits: ${self:custom.tableThroughput}
functions:
  health:
    handler: program.health
    events:
      - http:
          path: health
          method: get
          cors:
            origin: '*'
            headers:
              - partner
              - authorization
              - content-type
  getAll:
    handler: program.getAll
    memorySize: 1024
    timeout: 20
    events:
      - http:
          path: 'location/{locationId}'
          method: get
          cors:
            origin: '*'
            headers:
              - partner
              - authorization
              - content-type
  syncNew:
    handler: program.syncNew
    timeout: 60
    events:
      - schedule: rate(2 hours)
      # - schedule: rate(60 minutes)
      # - schedule: cron(0 5 * * ? *) # every day @ 1am eastern
      # - schedule: cron(0 13 * * ? *) # every day @ 9am eastern
      # - schedule: cron(0 21 * * ? *) # every day @ 5pm eastern
      - http:
          path: 'sync'
          method: post
          cors:
            origin: '*'
            headers:
              - partner
              - authorization
              - content-type
  syncByRegion:
    handler: program.syncByRegion
    memorySize: 1024
    timeout: 60
    environment:
      # newProgramTopicArn: ${self:custom.newProgramTopicArn.${self:provider.stage}}
      newProgramTopicArn: ${self:custom.newProgramTopicArn.deployed}
  consumeNewProgram:
    memorySize: 512
    # timeout: 20
    handler: program.consumeNewProgram
    description: Consume new program queue and add description
    reservedConcurrency: 1
    events:
      - sqs:
          arn: !GetAtt
            - newProgramQueue
            - Arn
          batchSize: 1
