service: remote
frameworkVersion: '>=1.1.0 <2.0.0'
provider:
  name: aws
  runtime: nodejs8.10
  environment:
    stage: ${self:custom.stage}
    losantKey: ${env:losantKey}
    losantSecret: ${env:losantSecret}
    losantAppId: ${env:losantAppId}

plugins:
  - serverless-domain-manager

custom:
  stage: ${opt:stage, self:provider.stage}
  domains:
    prod: api.tryclicker.com
    release: api-release.tryclicker.com
    dev: api-dev.tryclicker.com
  customDomain:
    domainName: ${self:custom.domains.${self:custom.stage}}
    basePath: remote
    certificateName: 'api.tryclicker.com'
    stage: ${self:custom.stage}
    createRoute53Record: true
    endpointType: 'edge'

functions:
  health:
    handler: remote.health
    events:
      - http:
          path: health
          method: get
          cors: true
  create:
    handler: remote.command
    events:
      - http:
          path: command
          method: post
          cors: true
