service: remote
frameworkVersion: '>=1.1.0 <2.0.0'
provider:
  name: aws
  memorySize: 128
  versionFunctions: false
  runtime: nodejs8.10
  deploymentBucket:
    name: serverless-deploys-clicker
  environment:
    stage: ${self:custom.stage}
    losantAppId: ${env:LOSANT_APP_ID}
    losantAccessToken: ${env:LOSANT_ACCESS_TOKEN}
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - dynamodb:*
        - lambda:InvokeFunction
        - lambda:InvokeAsync
      Resource: '*'
plugins:
  - serverless-domain-manager
  - serverless-prune-plugin
  - serverless-sentry

custom:
  stage: ${opt:stage, self:provider.stage}
  prune:
    automatic: true
    number: 3
  domains:
    prod: api.tryclicker.com
    release: api-release.tryclicker.com
    develop: api-develop.tryclicker.com
  customDomain:
    domainName: ${self:custom.domains.${self:custom.stage}}
    basePath: remote
    certificateName: 'api.tryclicker.com'
    stage: ${self:custom.stage}
    createRoute53Record: true
    endpointType: 'edge'
  sentry:
    dsn: ${env:SENTRY_DSN_ENDPOINT}
functions:
  health:
    handler: remote.health
    events:
      - http:
          path: health
          method: get
          cors:
            origin: '*'
            headers:
              - partner
              - authorization
              - content-type
  command:
    handler: remote.command
    memorySize: 512
    events:
      - http:
          path: '/command'
          method: post
          cors:
            origin: '*'
            headers:
              - partner
              - authorization
              - content-type
  checkBoxInfo:
    handler: remote.checkBoxInfo
    events:
      - http:
          path: '/box/info'
          method: post
          cors:
            origin: '*'
            headers:
              - partner
              - authorization
              - content-type
  checkBoxesInfo:
    handler: remote.checkBoxesInfo
    events:
      - http:
          path: '/boxes/info'
          method: post
          cors:
            origin: '*'
            headers:
              - partner
              - authorization
              - content-type
  debug:
    handler: remote.debug
    events:
      - http:
          path: '/debug'
          method: post
          cors:
            origin: '*'
            headers:
              - partner
              - authorization
              - content-type
