service: job
frameworkVersion: '>=1.1.0 <2.0.0'
provider:
  name: aws
  region: eu-central-1 # Germany
  versionFunctions: false
  runtime: nodejs8.10
  deploymentBucket:
    name: serverless-deploys-clicker-eu-central-1
  environment:
    stage: ${self:custom.stage}
    segmentWriteKey: ${self:custom.segmentKey.${self:custom.stage}}
    airtableKey: ${env:AIRTABLE_KEY}
    airtableBase: ${self:custom.airtableBase.${self:custom.stage}}
    slackControlCenterWebhookUrl: ${env:SLACK_CONTROL_CENTER_WEBHOOK_URL}
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - dynamodb:*
        - lambda:InvokeFunction
        - lambda:InvokeAsync
      Resource: '*'
plugins:
  - serverless-prune-plugin
  - serverless-deployment-bucket

custom:
  stage: ${opt:stage}
  prune:
    automatic: true
    number: 3
  segmentKey:
    prod: ${env:SEGMENT_WRITE_KEY}
    release: ${env:SEGMENT_WRITE_KEY_DEV}
    develop: ${env:SEGMENT_WRITE_KEY_DEV}
  airtableBase:
    prod: ${env:AIRTABLE_BASE}
    release: ${env:AIRTABLE_BASE_RELEASE}
    develop: ${env:AIRTABLE_BASE_DEV}

functions:
  health:
    handler: job.health
    events:
      - http:
          path: health
          method: get
          cors:
            origin: '*'
            headers:
              - partner
              - authorization
              - content-type
  controlCenter:
    handler: job.controlCenter
    timeout: 30
    events:
      - schedule: cron(*/5 * * * ? *)
      - http:
          path: 'control-center'
          method: post
          cors:
            origin: '*'
            headers:
              - partner
              - authorization
              - content-type
  updateGameStatus:
    handler: job.updateGameStatus
    timeout: 30
    events:
      - schedule: cron(*/1 * * * ? *)
      - http:
          path: 'game-status'
          method: post
          cors:
            origin: '*'
            headers:
              - partner
              - authorization
              - content-type
  controlCenterDailyInit:
    handler: job.controlCenterDailyInit
    timeout: 30
    events:
      - schedule: cron(59 9 * * ? *) # every day @ 5:59am eastern
      - http:
          path: 'control-center/daily'
          method: post
          cors:
            origin: '*'
            headers:
              - partner
              - authorization
              - content-type
