service: job
frameworkVersion: '>=1.1.0 <2.0.0'
provider:
  name: aws
  memorySize: 128
  region: eu-central-1 # Germany
  versionFunctions: false
  runtime: nodejs12.x
  # tracing: true
  logRetentionInDays: 14
  deploymentBucket:
    name: serverless-deploys-clicker-eu-central-1
  environment:
    stage: ${self:custom.stage}
    airtableKey: ${env:AIRTABLE_KEY}
    airtableBase: ${self:custom.airtableBase.${self:custom.stage}}
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - dynamodb:*
        - lambda:InvokeFunction
        - lambda:InvokeAsync
        - xray:PutTraceSegments
        - xray:PutTelemetryRecords
      Resource: '*'
plugins:
  - serverless-prune-plugin
  - serverless-deployment-bucket
  - serverless-sentry
  - serverless-dotenv-plugin
  - serverless-plugin-tracing

custom:
  stage: ${opt:stage}
  prune:
    automatic: true
    number: 3
  airtableBase:
    prod: ${env:AIRTABLE_BASE}
    release: ${env:AIRTABLE_BASE_RELEASE}
    develop: ${env:AIRTABLE_BASE_DEV}
  sentry:
    dsn: ${env:SENTRY_DSN_ENDPOINT}
  dotenv:
    basePath: ../
functions:
  controlCenterRun:
    handler: job.controlCenterRun
    events:
      - schedule: cron(*/10 * * * ? *) # every 10th minute
      - http:
          path: control-center
          method: post
  health:
    handler: job.health
    events:
      - http:
          path: health
          method: get
