service: location
frameworkVersion: '>=1.1.0 <2.0.0'
provider:
  name: aws
  runtime: nodejs8.10
  environment:
    stage: ${self:custom.stage}

plugins:
  - serverless-domain-manager

custom:
  stage: ${opt:stage, self:provider.stage}
  domains:
    prod: api.tryclicker.com
    release: api-release.tryclicker.com
    dev: api-dev.tryclicker.com
  customDomain:
    domainName: ${self:custom.domains.${self:custom.stage}}
    basePath: locations
    certificateName: 'api.tryclicker.com'
    stage: ${self:custom.stage}
    createRoute53Record: true
    endpointType: 'edge'

functions:
  health:
    handler: location.health
    events:
      - http:
          path: health
          method: get
          cors: true
  all:
    handler: location.all
    events:
      - http:
          path: ''
          method: get
          cors: true
  update:
    handler: location.update
    events:
      - http:
          path: { id }
          method: put
          cors: true
