frameworkVersion: ${file(../serverless.base.yml):frameworkVersion}
plugins: ${file(../serverless.base.yml):plugins}
custom: ${file(../serverless.base.yml):custom}
provider:
  name: ${file(../serverless.base.yml):provider.name}
  runtime: ${file(../serverless.base.yml):provider.runtime}
  # environment:

service: location

functions:
  health:
    handler: location.health
    events:
      - http:
          path: health
          method: get
          cors: true
  all:
    handler: location.all
    events:
      - http:
          path: ''
          method: get
          cors: true
  update:
    handler: location.update
    events:
      - http:
          path: { id }
          method: put
          cors: true
