name: mirror web/antenna-pwa
on:
  push:
    paths:
      - "web/antenna-pwa/**"

jobs:
  mirror:
    name: mirror
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: mirror deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: git@github.com:teamclicker/clicker-antenna-pwa-mirror.git
          BRANCH: ${GITHUB_REF##*/}
          FOLDER: web/antenna-pwa
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY_PWA }}
          MESSAGE: "{msg} [{sha}]"
