name: deploy serverless functions
on:
  push:
    paths:
      - "functions/location/**"
    branches:
      - master
      - release
      - develop

jobs:
  serverless:
    name: serverless
    runs-on: ubuntu-latest
    defaults:
      run:
        # shell: bash
        working-directory: functions/location
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/functions/location/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install NPM dependencies
        # working-directory: ./functions/location
        run: npm install
      - name: Build if needed
        # working-directory: ./functions/location
        run: npm run build --if-present
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy Lambda functions develop
        env:
          SENTRY_DSN_ENDPOINT: ${{ secrets.SENTRY_DSN_ENDPOINT }}
        # working-directory: ./functions/location
        if: github.ref == 'refs/heads/develop'
        run: SLS_DEBUG=* npx serverless deploy --stage develop --verbose
