name: clicker workflow
on:
  push:
    branches:
      - develop
      - release
      - master
    paths:
      - "web/app/**"

jobs:
  web:
    name: landing page mirror
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Mirror
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: git@github.com:teamclicker/clicker-landing-mirror.git
          BRANCH: ${GITHUB_REF##*/}
          FOLDER: web/app
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY_LANDING }}
          MESSAGE: "{msg} [{sha}]"
