name: clicker workflow
on:
  push:
    branches:
      - develop
      - release
      - master
    paths:
      - "web/app/**"

jobs:
  web:
    name: landing page mirror
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: spyoungtech/mirror-action@master
        with:
          args: "https://github.com/teamclicker/clicker-landing-mirror"
        env:
          GIT_USERNAME: teamclicker
          GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
