name: clicker workflow
on:
  push:
    branches:
      - develop
      - release
      - master
    paths:
      - "web/app/**"

jobs:
  web:
    name: landing page mirror
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: publish:starters
        uses: johno/actions-push-subdirectories@master
        env:
          API_TOKEN_GITHUB: ${{ secrets.GITHUB_API_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: web/app teamclicker clicker-landing-mirror
