name: clicker workflow
on:
  push:
    branches:
      - develop
      - release
      - master
    paths:
      - "web/app/**"

jobs:
  web:
    name: landing page mirror
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      # - uses: spyoungtech/mirror-action@master
      #   with:
      #     # args: "https://github.com/teamclicker/clicker-landing-mirror.git"
      #     # env:
      #     # spyoungtech/mirror-action
      #     REMOTE: "https://github.com/teamclicker/clicker-landing-mirror.git"
      #     GIT_USERNAME: teamclicker
      #     GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
      #     # GIT_SSH_PRIVATE_KEY: ${{ secrets.GIT_SSH_KEY }}
      - name: Mirror
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: https://github.com/teamclicker/clicker-landing-mirror.git
          BRANCH: ${GITHUB_REF##*/}
          FOLDER: web/app
          # SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          # KNOWN_HOSTS_FILE: resources/known_hosts # Needed if target repo is not on github.com
