name: End-to-end tests
on:
  push:
    branches:
      - develop
      - release
    paths:
      - "functions/**"
      - "mobile/app/**"
jobs:
  e2e:
    name: mobile app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install app dependencies
        uses: bahmutov/npm-install@v1
        with:
          working-directory: mobile/app
      - name: Start server in the background
        run: pwd && ls && npm run start:wait
        working-directory: mobile/app
      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          working-directory: mobile/app
          record: true
          headless: true
          # start: npm run e2e:headless
          # wait-on: "http://localhost:4100"
          # browser: chrome
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
