name: End-to-end tests
on:
  push:
    branches:
      - develop
      - release
    paths:
      - "functions/**"
      - "mobile/app/**"
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    on:
      schedule:
        - cron: "0 9,21 * * * "
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          start: npm start
          working-directory: mobile/app/e2e
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
