name: End-to-end tests
on:
  push:
    branches:
      - "*"
      - "!master"
    paths:
      - "functions/**"
      - "mobile/app/**"
jobs:
  e2e:
    name: mobile app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Extract branch name
        shell: bash
        run: |
          branch=${GITHUB_REF##*/}
          echo $branch
          if [ branch == "master" ]; then
            echo "::set-env ENV=production"
            echo "::set-env cypress_apiBaseUrl=https://api.tryclicker.com"
          fi
          if [ branch == "release" ]; then
            echo "::set-env ENV=release"
            echo "::set-env cypress_apiBaseUrl=https://api-release.tryclicker.com"
          fi
          if [ branch == "develop" ]; then
            echo "::set-env ENV=develop"
          fi
      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          working-directory: mobile/app
          build: npm run build
          start: npm run start:static
          wait-on: "http://localhost:4100"
          browser: chrome
          record: true
          headless: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
